Background,Text
"<%AppName%>"

Background,Title
"<%AppName%> Setup"

ChooseComponents,BackButton
"< <%Back%>"

ChooseComponents,CancelButton
"<%Cancel%>"

ChooseComponents,Caption
"Wählen Sie die zu installierenden Komponenten aus und deselektieren Sie die Komponenten, die Sie nicht installieren möchten."

ChooseComponents,ComponentLabel
"Komponenten"

ChooseComponents,DescriptionLabel
"Beschreibung"

ChooseComponents,NextButton
"<%Next%> >"

ChooseComponents,SpaceRequiredLabel
"<%SpaceRequiredText%> an Plattenplatz benötigt"

ChooseComponents,Title
"Benutzerdefinierte Einstellungen"

CopyFiles,CancelButton
"<%Cancel%>"

CopyFiles,Caption
"<%GroupBeingInstalledText%>"

CopyFiles,Message
"<%Status%>"

CopyFiles,ProgressValue
"<%InstallPercentComplete%>"

CopyFiles,Title
"Kopiere Dateien"

CustomBlankPane1,BackButton
"< <%Back%>"

CustomBlankPane1,CancelButton
"<%Cancel%>"

CustomBlankPane1,NextButton
"<%Next%> >"

CustomBlankPane1,Title
"<%AppName%> Setup"

CustomTextPane1,BackButton
"< <%Back%>"

CustomTextPane1,CancelButton
"<%Cancel%>"

CustomTextPane1,Caption
"Überschrift"

CustomTextPane1,Message
"Meldung"

CustomTextPane1,NextButton
"<%Next%> >"

CustomTextPane1,Title
"Titel"

CustomTextPane2,BackButton
"< <%Back%>"

CustomTextPane2,CancelButton
"<%Cancel%>"

CustomTextPane2,Caption
"Überschrift"

CustomTextPane2,NextButton
"<%Next%> >"

CustomTextPane2,Text
"Text kommt hier hin."

CustomTextPane2,Title
"<%AppName%> Setup"

CustomTextPane3,BackButton
"< <%Back%>"

CustomTextPane3,CancelButton
"<%No%>"

CustomTextPane3,Caption
"Überschrift"

CustomTextPane3,Message
"Meldung"

CustomTextPane3,NextButton
"<%Yes%>"

CustomTextPane3,Text
"Text kommt hier hin."

CustomTextPane3,Title
"Title"

License,AcceptCheck
"Ich akzeptiere die Lizenzbestimmungen."

License,BackButton
"< <%Back%>"

License,CancelButton
"Nein"

License,Caption
"Bitte lesen Sie die folgenden Lizenzbestimmungen.  Press the PAGE DOWN key to see the rest of the agreement."

License,Message
"Akzeptieren Sie die vorangegangenen Lizenzbestimmungen?  Wenn Sie Nein wählen, wird die Installation beendet.  Um <%AppName%> zu installieren, müssen Sie den Lizenzbestimmungen zustimmen."

License,NextButton
"Ja"

License,Text
"Hier kommen Ihre Lizenzbestimmungen hin."

License,Title
"Lizenzbestimmungen"

Readme,BackButton
"< <%Back%>"

Readme,CancelButton
"<%Cancel%>"

Readme,NextButton
"<%Next%> >"

Readme,Text
"Hier kommen Ihre Liesmich Informationen hin."

Readme,Title
"Liesmich Informationen"

SelectDestination,BackButton
"< <%Back%>"

SelectDestination,BrowseButton
"<%Browse%>"

SelectDestination,CancelButton
"<%Cancel%>"

SelectDestination,Caption
"Setup wird <%AppName%> in das folgende Verzeichnis installieren.  

Klicken Sie auf Weiter, wenn dieses Verzeichnis verwendet werden soll.  

Um ein anderes Verzeichnis auszuwählen, klicken Sie auf Durchsuchen 

Möchten Sie <%AppName%> nicht installieren, dann klicken Sie auf Abbrechen, um das Setup zu verlassen."

SelectDestination,DestinationLabel
"Zielordner"

SelectDestination,NextButton
"<%Next%> >"

SelectDestination,Title
"Auswahl Installationsziel"

SelectProgramFolder,AllUsersCheckbutton
"Erstelle Programmordner für alle Benutzer"

SelectProgramFolder,BackButton
"< <%Back%>"

SelectProgramFolder,CancelButton
"<%Cancel%>"

SelectProgramFolder,Caption
"Setup wird die Programmsymbole zum unten aufgeführten Programmordner hinzufügen.  Sie können einen neuen Ordnernamen eingeben oder einen von der von der existierenden Ordnerliste auswählen.  Klicken Sie auf Weiter um Fortzufahren."

SelectProgramFolder,FolderListLabel
"Vorhandene Ordner:"

SelectProgramFolder,NextButton
"<%Next%> >"

SelectProgramFolder,ProgramFolderLabel
"Programmordner:"

SelectProgramFolder,Title
"Auswahl Programmordner"

Setup,Caption
"Setup bereitet den InstallJammer Assistenten vor, der Sie durch den Rest des Installationsvorgang führen wird.  Bitte warten Sie."

Setup,Title
"Setup"

SetupComplete,BackButton
"< <%Back%>"

SetupComplete,CancelButton
"<%Cancel%>"

SetupComplete,Caption
"Setup hat die Installation von <%AppName%> auf Ihrem Computer beendet."

SetupComplete,NextButton
"<%Finish%>"

SetupComplete,Text
"Klicken Sie auf Beenden, um Setup zu verlassen."

SetupComplete,Title
"Setup Vollständig"

SetupType,BackButton
"< <%Back%>"

SetupType,CancelButton
"<%Cancel%>"

SetupType,Caption
"Klicken Sie auf die bevorzugte Art des Setup, dann auf Weiter."

SetupType,NextButton
"<%Next%> >"

SetupType,Title
"Setup Art"

StartCopyingFiles,BackButton
"< <%Back%>"

StartCopyingFiles,CancelButton
"<%Cancel%>"

StartCopyingFiles,Caption
"Setup hat genug Informationen, um die Programmdateien zu kopieren.  Wenn Sie die Einstellungen überprüfen oder ändern möchten, klicken Sie auf Zurück.  Wenn Sie mit den Einstellungen zufrieden sind, klicken Sie auf Weiter, um mit dem Kopieren der Dateien zu beginnen.  

Derzeitige Einstellungen:"

StartCopyingFiles,NextButton
"<%Next%> >"

StartCopyingFiles,Text
"Install Directory:
 	<%InstallDir%>

 Setup Type:
 	<%InstallType%>"

StartCopyingFiles,Title
"Start Copying Files"

Uninstall,BackButton
"< <%Back%>"

Uninstall,CancelButton
"<%Cancel%>"

Uninstall,Caption
"<%GroupBeingUninstalledText%>"

Uninstall,Message
"<%Status%>"

Uninstall,NextButton
"<%Next%> >"

Uninstall,ProgressValue
"<%UninstallPercentComplete%>"

Uninstall,Title
"Deinstallation <%AppName%>"

UninstallComplete,Caption
"Deinstallation erfolgreich abgeschlossen."

UninstallComplete,FinishButton
"<%Finish%>"

UninstallComplete,Title
"Deinstallation Abgeschlossen"

UninstallDetails,Caption
"Die folgenden Fehler sind beim Löschen aufgetreten:"

UninstallDetails,Errors
"<%Errors%>"

UninstallDetails,FinishButton
"<%Finish%>"

UninstallDetails,Title
"Deinstallation Details"

UserInformation,BackButton
"< <%Back%>"

UserInformation,CancelButton
"<%Cancel%>"

UserInformation,Caption
"Bitte geben Sie Ihren Namen und den Namen der Firma ein, für die Sie arbeiten."

UserInformation,CompanyLabel
"Firma:"

UserInformation,NameLabel
"Name:"

UserInformation,NextButton
"<%Next%> >"

UserInformation,Title
"Benutzer Information"

Welcome,BackButton
"< <%Back%>"

Welcome,CancelButton
"<%Cancel%>"

Welcome,Caption
"Willkommen zum Setup von <%AppName%>.  Dieses Programm wird <%AppName%> auf Ihrem Computer installieren."

Welcome,Message
"Es wird empfohlen, das Sie alle anderen Anwendungen schließen, bevor Sie fortfahren.

Klicken Sie auf Weiter um Fortzufahren.

WARNUNG: Dies Programm ist urheberrechtlich geschützt.  Nicht authorisierte Vervielfältigung oder Verbreitung von diesem Programm oder Teilen dessen, können zu erheblichen Strafen führen und diese werden nach maximalen Möglichkeiten der geltenden Gesetze angewendet."

Welcome,NextButton
"<%Next%> >"

Welcome,Title
"Willkommen"
