Background,Text
"<%AppName%>"

Background,Title
"<%AppName%> Setup"

ChooseComponents,BackButton
"< <%Back%>"

ChooseComponents,CancelButton
"<%Cancel%>"

ChooseComponents,Caption
"Select the components you want to install and deselect the components you do not want to install."

ChooseComponents,ComponentLabel
"Components"

ChooseComponents,DescriptionLabel
"Description"

ChooseComponents,NextButton
"<%Next%> >"

ChooseComponents,SpaceRequiredLabel
"Space Required: <%SpaceRequiredText%>"

ChooseComponents,Title
"Custom Setup"

CopyFiles,CancelButton
"<%Cancel%>"

CopyFiles,Caption
"<%GroupBeingInstalledText%>"

CopyFiles,Message
"<%Status%>"

CopyFiles,ProgressValue
"<%InstallPercentComplete%>"

CopyFiles,Title
"Copying Files"

CustomBlankPane1,BackButton
"< <%Back%>"

CustomBlankPane1,CancelButton
"<%Cancel%>"

CustomBlankPane1,NextButton
"<%Next%> >"

CustomBlankPane1,Title
"<%AppName%> Setup"

CustomTextPane1,BackButton
"< <%Back%>"

CustomTextPane1,CancelButton
"<%Cancel%>"

CustomTextPane1,Caption
"Caption"

CustomTextPane1,Message
"Message"

CustomTextPane1,NextButton
"<%Next%> >"

CustomTextPane1,Title
"Title"

CustomTextPane2,BackButton
"< <%Back%>"

CustomTextPane2,CancelButton
"<%Cancel%>"

CustomTextPane2,Caption
"Caption"

CustomTextPane2,NextButton
"<%Next%> >"

CustomTextPane2,Text
"Text goes here."

CustomTextPane2,Title
"<%AppName%> Setup"

CustomTextPane3,BackButton
"< <%Back%>"

CustomTextPane3,CancelButton
"<%No%>"

CustomTextPane3,Caption
"Caption"

CustomTextPane3,Message
"Message"

CustomTextPane3,NextButton
"<%Yes%>"

CustomTextPane3,Text
"Text goes here."

CustomTextPane3,Title
"Title"

License,AcceptCheck
"I accept the terms of this license agreement."

License,BackButton
"< <%Back%>"

License,CancelButton
"No"

License,Caption
"Please read the following License Agreement.  Press the PAGE DOWN key to see the rest of the agreement."

License,Message
"Do you accept all the terms of the preceding License Agreement?  If you choose No, Setup will close.  To install <%AppName%>, you must accept this agreement."

License,NextButton
"Yes"

License,Text
"Put your license agreement here."

License,Title
"License Agreement"

Readme,BackButton
"< <%Back%>"

Readme,CancelButton
"<%Cancel%>"

Readme,NextButton
"<%Next%> >"

Readme,Text
"Put your readme information here."

Readme,Title
"Readme Information"

SelectDestination,BackButton
"< <%Back%>"

SelectDestination,BrowseButton
"<%Browse%>"

SelectDestination,CancelButton
"<%Cancel%>"

SelectDestination,Caption
"Setup will install <%AppName%> in the following folder.

To install to this folder, click Next.

To install to a different folder, click Browse and select another folder.

You can choose not to install <%AppName%> by clicking Cancel to exit Setup."

SelectDestination,DestinationLabel
"Destination Folder"

SelectDestination,NextButton
"<%Next%> >"

SelectDestination,Title
"Select Destination Location"

SelectProgramFolder,AllUsersCheckbutton
"Create program folder for all users"

SelectProgramFolder,BackButton
"< <%Back%>"

SelectProgramFolder,CancelButton
"<%Cancel%>"

SelectProgramFolder,Caption
"Setup will add the program icons to the Program Folder listed below.  You may type a new folder name or select from the existing folders list.  Click Next to continue."

SelectProgramFolder,FolderListLabel
"Exising Folders:"

SelectProgramFolder,NextButton
"<%Next%> >"

SelectProgramFolder,ProgramFolderLabel
"Program Folder:"

SelectProgramFolder,Title
"Select Program Folder"

Setup,Caption
"Setup is preparing the InstallJammer Wizard which will guide you through the rest of the setup process.  Please wait."

Setup,Title
"Setup"

SetupComplete,BackButton
"< <%Back%>"

SetupComplete,CancelButton
"<%Cancel%>"

SetupComplete,Caption
"Setup has finished installing <%AppName%> on your computer."

SetupComplete,NextButton
"<%Finish%>"

SetupComplete,Text
"Click Finish to complete Setup."

SetupComplete,Title
"Setup Complete"

SetupType,BackButton
"< <%Back%>"

SetupType,CancelButton
"<%Cancel%>"

SetupType,Caption
"Click the type of Setup you prefer, then click Next."

SetupType,NextButton
"<%Next%> >"

SetupType,Title
"Setup Type"

StartCopyingFiles,BackButton
"< <%Back%>"

StartCopyingFiles,CancelButton
"<%Cancel%>"

StartCopyingFiles,Caption
"Setup has enough information to start copying the program files.  If you want to review or change any settings, click Back.  If you are satisfied with the settings, click Next to begin copying files.  

Current Settings:"

StartCopyingFiles,NextButton
"<%Next%> >"

StartCopyingFiles,Text
"Install Directory:
 	<%InstallDir%>

 Setup Type:
 	<%InstallType%>"

StartCopyingFiles,Title
"Start Copying Files"

Uninstall,BackButton
"< <%Back%>"

Uninstall,CancelButton
"<%Cancel%>"

Uninstall,Caption
"<%GroupBeingUninstalledText%>"

Uninstall,Message
"<%Status%>"

Uninstall,NextButton
"<%Next%> >"

Uninstall,ProgressValue
"<%UninstallPercentComplete%>"

Uninstall,Title
"Uninstall <%AppName%>"

UninstallComplete,Caption
"Uninstall Completes Successfully."

UninstallComplete,FinishButton
"<%Finish%>"

UninstallComplete,Title
"Uninstall Complete"

UninstallDetails,Caption
"The following errors occurred during uninstall:"

UninstallDetails,Errors
"<%Errors%>"

UninstallDetails,FinishButton
"<%Finish%>"

UninstallDetails,Title
"Uninstall Details"

UserInformation,BackButton
"< <%Back%>"

UserInformation,CancelButton
"<%Cancel%>"

UserInformation,Caption
"Type your name and the company you work for below."

UserInformation,CompanyLabel
"Company:"

UserInformation,NameLabel
"Name:"

UserInformation,NextButton
"<%Next%> >"

UserInformation,Title
"User Information"

Welcome,BackButton
"< <%Back%>"

Welcome,CancelButton
"<%Cancel%>"

Welcome,Caption
"Welcome to the <%AppName%> Setup program.  This program will install <%AppName%> on your computer."

Welcome,Message
"It is strongly recommended that you exit all Windows programs you have running.  Click Next to continue with the Setup program.

WARNING: This program is protected by copyright law and international treaties.

Unauthorized reproduction or distribution of this program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under law."

Welcome,NextButton
"<%Next%> >"

Welcome,Title
"Welcome Screen"
