Background,Text
"<%AppName%>"

Background,Title
"Instalación de <%AppName%>"

ChooseComponents,BackButton
"< <%Back%>"

ChooseComponents,CancelButton
"<%Cancel%>"

ChooseComponents,Caption
"Seleccione los componentes que desea instalar y elimine aquéllos que no desea que sean instalados."

ChooseComponents,ComponentLabel
"Componentes"

ChooseComponents,DescriptionLabel
"Descripción"

ChooseComponents,NextButton
"<%Next%> >"

ChooseComponents,SpaceRequiredLabel
"Espacio Requerido: <%SpaceRequiredText%>"

ChooseComponents,Title
"Instalación Personalizada"

CopyFiles,CancelButton
"<%Cancel%>"

CopyFiles,Caption
"<%GroupBeingInstalledText%>"

CopyFiles,Message
"<%Status%>"

CopyFiles,ProgressValue
"<%InstallPercentComplete%>"

CopyFiles,Title
"Copiando Archivos"

CustomBlankPane1,BackButton
"< <%Back%>"

CustomBlankPane1,CancelButton
"<%Cancel%>"

CustomBlankPane1,NextButton
"<%Next%> >"

CustomBlankPane1,Title
"Instalación de <%AppName%>"

CustomTextPane1,BackButton
"< <%Back%>"

CustomTextPane1,CancelButton
"<%Cancel%>"

CustomTextPane1,Caption
"Leyenda"

CustomTextPane1,Message
"Mensaje"

CustomTextPane1,NextButton
"<%Next%> >"

CustomTextPane1,Title
"Título"

CustomTextPane2,BackButton
"< <%Back%>"

CustomTextPane2,CancelButton
"<%Cancel%>"

CustomTextPane2,Caption
"Leyenda"

CustomTextPane2,NextButton
"<%Next%> >"

CustomTextPane2,Text
"Texto aquí."

CustomTextPane2,Title
"Instalación de <%AppName%>"

CustomTextPane3,BackButton
"< <%Back%>"

CustomTextPane3,CancelButton
"<%No%>"

CustomTextPane3,Caption
"Leyenda"

CustomTextPane3,Message
"Mensaje"

CustomTextPane3,NextButton
"<%Yes%>"

CustomTextPane3,Text
"Texto aquí."

CustomTextPane3,Title
"Título"

License,AcceptCheck
"Acepto los términos de este Acuerdo de Licencia."

License,BackButton
"< <%Back%>"

License,CancelButton
"No"

License,Caption
"Por favor lea el siguiente Acuerdo de Licencia.  Presione Av.Pag para ver el resto del acuerdo."

License,Message
"¿Acepta los terminos del Acuerdo de Licencia anterior?  Si escoge No, la instalación se cerrara.  Para instalar <%AppName%>, debe aceptar este acuerdo."

License,NextButton
"Sí"

License,Text
"Ponga aquí su Acuerdo de Licencia."

License,Title
"Acuerdo de Licencia"

Readme,BackButton
"< <%Back%>"

Readme,CancelButton
"<%Cancel%>"

Readme,NextButton
"<%Next%> >"

Readme,Text
"Ponga aqui su Léame."

Readme,Title
"Léame"

SelectDestination,BackButton
"< <%Back%>"

SelectDestination,BrowseButton
"<%Browse%>"

SelectDestination,CancelButton
"<%Cancel%>"

SelectDestination,Caption
"Se instalará <%AppName%> en la siguiente carpeta.

Para instalar en esta carpeta, pulse Siguiente.

Para instalar en una carpeta diferente, pulse Examinar y seleccione otra carpeta.

Puede escoger no instalar <%AppName%> pulsando Cancelar para salir de la instalación."

SelectDestination,DestinationLabel
"Carpeta Destino"

SelectDestination,NextButton
"<%Next%> >"

SelectDestination,Title
"Seleccione carpeta destino"

SelectProgramFolder,AllUsersCheckbutton
"Crear grupo de programas para todos los usuarios"

SelectProgramFolder,BackButton
"< <%Back%>"

SelectProgramFolder,CancelButton
"<%Cancel%>"

SelectProgramFolder,Caption
"Se instalarán iconos en el Grupo de Programas siguiente.  Puede escribir un nuevo nombre de grupo o seleccionarlo de la lista de grupos existentes.  Pulse Siguiente para continuar."

SelectProgramFolder,FolderListLabel
"Grupos Existentes:"

SelectProgramFolder,NextButton
"<%Next%> >"

SelectProgramFolder,ProgramFolderLabel
"Grupo de Programas:"

SelectProgramFolder,Title
"Seleccione Grupo de Programas"

Setup,Caption
"El programa de instalación está preparando el Wizard InstallJammer, que le guiara a través del proceso de instalación.  Por favor espere."

Setup,Title
"Instalación"

SetupComplete,BackButton
"< <%Back%>"

SetupComplete,CancelButton
"<%Cancel%>"

SetupComplete,Caption
"Se ha finalizado la instalación de <%AppName%> en su equipo."

SetupComplete,NextButton
"<%Finish%>"

SetupComplete,Text
"Pulse Finalizar para completar la instalación."

SetupComplete,Title
"Instalación Completa"

SetupType,BackButton
"< <%Back%>"

SetupType,CancelButton
"<%Cancel%>"

SetupType,Caption
"Seleccione el tipo de instalación que prefiere, y pulse Siguiente."

SetupType,NextButton
"<%Next%> >"

SetupType,Title
"Tipo de Instalación"

StartCopyingFiles,BackButton
"< <%Back%>"

StartCopyingFiles,CancelButton
"<%Cancel%>"

StartCopyingFiles,Caption
"Se ha recopilado la información necesaria para comenzar a copiar los archivos del programa.  Si desea revisar o cambiar la configuración, pulse Atrás.  Si esta conforme con la configuración, pulse Siguiente para comenzar a copiar los archivos.
 

Configuración actual:"

StartCopyingFiles,NextButton
"<%Next%> >"

StartCopyingFiles,Text
"Directorio de Instalación:
 	<%InstallDir%>

 Tipo de Instalación:
 	<%InstallType%>"

StartCopyingFiles,Title
"Comenzar a Copiar Archivos"

Uninstall,BackButton
"< <%Back%>"

Uninstall,CancelButton
"<%Cancel%>"

Uninstall,Caption
"<%GroupBeingUninstalledText%>"

Uninstall,Message
"<%Status%>"

Uninstall,NextButton
"<%Next%> >"

Uninstall,ProgressValue
"<%UninstallPercentComplete%>"

Uninstall,Title
"Desinstalación de <%AppName%>"

UninstallComplete,Caption
"La Desinstalación se completó con exito."

UninstallComplete,FinishButton
"<%Finish%>"

UninstallComplete,Title
"Desinstalación Completa"

UninstallDetails,Caption
"Ocurrieron los siguientes errores durante el proceso de desinstalación:"

UninstallDetails,Errors
"<%Errors%>"

UninstallDetails,FinishButton
"<%Finish%>"

UninstallDetails,Title
"Detalles de la Desinstalación"

UserInformation,BackButton
"< <%Back%>"

UserInformation,CancelButton
"<%Cancel%>"

UserInformation,Caption
"Escriba su nombre y empresa a continuación."

UserInformation,CompanyLabel
"Empresa:"

UserInformation,NameLabel
"Nombre:"

UserInformation,NextButton
"<%Next%> >"

UserInformation,Title
"Información de Usuario"

Welcome,BackButton
"< <%Back%>"

Welcome,CancelButton
"<%Cancel%>"

Welcome,Caption
"Bienvenido al programa de instalación de <%AppName%>.  Este programa instalará <%AppName%> en su equipo."

Welcome,Message
"Se recomienda salir de todos los programas Windows que este ejecutando.  Pulse Siguiente para continuar con el programa de instalación.

ADVERTENCIA: Este programa esta protegido con copyright y los acuerdos internacionales.


 La reproducción o distribución no autorizada de este programa, o parte del mismo, puede acarrear penas civiles y criminales, y será perseguida por la ley."

Welcome,NextButton
"<%Next%> >"

Welcome,Title
"Pantalla de Bievenida"
