Background,Text
"<%AppName%>"

Background,Title
"Installation <%AppName%>"

ChooseComponents,BackButton
"< <%Back%>"

ChooseComponents,CancelButton
"<%Cancel%>"

ChooseComponents,Caption
"Sélectionner les composants à installer et déselectionner les composants à ne pas installer."

ChooseComponents,ComponentLabel
"Composants"

ChooseComponents,DescriptionLabel
"Description"

ChooseComponents,NextButton
"<%Next%> >"

ChooseComponents,SpaceRequiredLabel
"Espace requis: <%SpaceRequiredText%>"

ChooseComponents,Title
"Installation personnalisée"

CopyFiles,CancelButton
"<%Cancel%>"

CopyFiles,Caption
"<%GroupBeingInstalledText%>"

CopyFiles,Message
"<%Status%>"

CopyFiles,ProgressValue
"<%InstallPercentComplete%>"

CopyFiles,Title
"Copie des fichiers"

CustomBlankPane1,BackButton
"< <%Back%>"

CustomBlankPane1,CancelButton
"<%Cancel%>"

CustomBlankPane1,NextButton
"<%Next%> >"

CustomBlankPane1,Title
"<%AppName%> Setup"

CustomTextPane1,BackButton
"< <%Back%>"

CustomTextPane1,CancelButton
"<%Cancel%>"

CustomTextPane1,Caption
"Légende"

CustomTextPane1,Message
"Message"

CustomTextPane1,NextButton
"<%Next%> >"

CustomTextPane1,Title
"Titre"

CustomTextPane2,BackButton
"< <%Back%>"

CustomTextPane2,CancelButton
"<%Cancel%>"

CustomTextPane2,Caption
"Légende"

CustomTextPane2,NextButton
"<%Next%> >"

CustomTextPane2,Text
"Saisir le texte ici."

CustomTextPane2,Title
"Installation <%AppName%>"

CustomTextPane3,BackButton
"< <%Back%>"

CustomTextPane3,CancelButton
"<%No%>"

CustomTextPane3,Caption
"Légende"

CustomTextPane3,Message
"Message"

CustomTextPane3,NextButton
"<%Yes%>"

CustomTextPane3,Text
"Saisir le texte ici."

CustomTextPane3,Title
"Titre"

License,AcceptCheck
"J'accepte les termes de cet accord de licence."

License,BackButton
"< <%Back%>"

License,CancelButton
"<%No%>"

License,Caption
"Lisez SVP l'accord de licence suivant.  Appuyez sur la touche PAGE DOWN pour lire la suite de l'accord de licence."

License,Message
"Acceptez-vous tous les termes du précédent accord de licence ?  Si vous choisissez Non, l'installation s'arrêtera.  Pour installer <%AppName%>, vous devez accepter cet accord de licence."

License,NextButton
"Oui"

License,Text
"Mettez votre accord de licence ici."

License,Title
"Accord de licence"

Readme,BackButton
"< <%Back%>"

Readme,CancelButton
"<%Cancel%>"

Readme,NextButton
"<%Next%> >"

Readme,Text
"Mettez les informations de votre Readme ici."

Readme,Title
"Readme"

SelectDestination,BackButton
"< <%Back%>"

SelectDestination,BrowseButton
"<%Browse%>"

SelectDestination,CancelButton
"<%Cancel%>"

SelectDestination,Caption
"L'installation de <%AppName%> s'effectuera dans le répertoire suivant.

Pour installer dans ce répertoire, cliquez sur le bouton SUIVANT.

Pour installer dans un autre répertoire, cliquez sur le bouton PARCOURIR et sélectionnez un autre répertoire.

Vous pouvez choisir de ne pas installer <%AppName%> en cliquant sur le bouton ANNULER pour sortir de l'installation."

SelectDestination,DestinationLabel
"Répertoire d'installation"

SelectDestination,NextButton
"<%Next%> >"

SelectDestination,Title
"Sélectionnez le répertoire d'installation"

SelectProgramFolder,AllUsersCheckbutton
"Créer le dossier programme pour tous les utilisateurs"

SelectProgramFolder,BackButton
"< <%Back%>"

SelectProgramFolder,CancelButton
"<%Cancel%>"

SelectProgramFolder,Caption
"L'installation ajoutera les icônes de programme au dossier Programme affiché ci-dessous.  Vous pouvez saisir un nouveau nom de dossier ou en sélectionner un dans la liste des dossiers existants.  Cliquez sur SUIVANT pour continuer."

SelectProgramFolder,FolderListLabel
"Dossiers existants :"

SelectProgramFolder,NextButton
"<%Next%> >"

SelectProgramFolder,ProgramFolderLabel
"Dossier Programme :"

SelectProgramFolder,Title
"Sélectionnez le dossier Programme"

Setup,Caption
"L'installation prépare l'assistant InstallJammer qui vous guidera tout au long du processus d'installation.  Patientez SVP."

Setup,Title
"Installation"

SetupComplete,BackButton
"< <%Back%>"

SetupComplete,CancelButton
"<%Cancel%>"

SetupComplete,Caption
"L'installation de <%AppName%> sur votre ordinateur est terminée."

SetupComplete,NextButton
"<%Finish%>"

SetupComplete,Text
"Cliquez sur TERMINER pour finir l'installation."

SetupComplete,Title
"Installation terminée"

SetupType,BackButton
"< <%Back%>"

SetupType,CancelButton
"<%Cancel%>"

SetupType,Caption
"Cliquez sur le type d'installation que vous souhaitez, puis cliquez sur SUIVANT."

SetupType,NextButton
"<%Next%> >"

SetupType,Title
"Type d'installation"

StartCopyingFiles,BackButton
"< <%Back%>"

StartCopyingFiles,CancelButton
"<%Cancel%>"

StartCopyingFiles,Caption
"L'installeur a maintenant assez d'informations pour commencer à copier les fichiers.  Si vous voulez revoir ou modifier le paramétrage, cliquez sur PRECEDENT.  Si vous êtes satisfait du paramétrage, cliquez sur suivant pour commencer à copier les fichiers.  

Paramétrage courant:"

StartCopyingFiles,NextButton
"<%Next%> >"

StartCopyingFiles,Text
"Répertoire d'installation:
 	<%InstallDir%>

 Type d'installation:
 	<%InstallType%>"

StartCopyingFiles,Title
"Copie des fichiers"

Uninstall,BackButton
"< <%Back%>"

Uninstall,CancelButton
"<%Cancel%>"

Uninstall,Caption
"<%GroupBeingUninstalledText%>"

Uninstall,Message
"<%Status%>"

Uninstall,NextButton
"<%Next%> >"

Uninstall,ProgressValue
"<%UninstallPercentComplete%>"

Uninstall,Title
"Désinstaller <%AppName%>"

UninstallComplete,Caption
"La désinstallation s'est bien terminée."

UninstallComplete,FinishButton
"<%Finish%>"

UninstallComplete,Title
"Désinstallation terminée"

UninstallDetails,Caption
"Les erreurs suivantes sont apparues pendant la désinstallation:"

UninstallDetails,Errors
"<%Errors%>"

UninstallDetails,FinishButton
"<%Finish%>"

UninstallDetails,Title
"Details de la désinstallation"

UserInformation,BackButton
"< <%Back%>"

UserInformation,CancelButton
"<%Cancel%>"

UserInformation,Caption
"Saisissez votre nom et votre société ci-dessous."

UserInformation,CompanyLabel
"Société:"

UserInformation,NameLabel
"Nom:"

UserInformation,NextButton
"<%Next%> >"

UserInformation,Title
"Informations sur l'utilisateur"

Welcome,BackButton
"< <%Back%>"

Welcome,CancelButton
"<%Cancel%>"

Welcome,Caption
"Bienvenue dans le programme d'installation de <%AppName%>.  Ce programme installera <%AppName%> sur votre ordinateur."

Welcome,Message
"Il est fortement recommandé de fermer tous les programmes en cours d'exécution.  Cliquez sur SUIVANT pour continuer l'installation.

ATTENTION: Ce programme est protégé par les lois du copyright et les traités internationaux.

Toute reproduction interdite ou distribution de ce programme, dans son intégralité ou en partie, entrainera des poursuites civils et criminelles, avec l'ampleur maximale autorisée par la loi."

Welcome,NextButton
"<%Next%> >"

Welcome,Title
"Ecran d'accueil"
