Background,Text
"<%AppName%>"

Background,Title
"<%AppName%> Telepítés"

ChooseComponents,BackButton
"< <%Back%>"

ChooseComponents,CancelButton
"<%Cancel%>"

ChooseComponents,Caption
"Válassza ki azokat a komponenseket, amelyeket fel akar telepíteni, és ne válassza ki azokat, amelyeket nem akar telepíteni."

ChooseComponents,ComponentLabel
"Komponensek"

ChooseComponents,DescriptionLabel
"Leírás"

ChooseComponents,NextButton
"<%Next%> >"

ChooseComponents,SpaceRequiredLabel
"Szükséges tárterület: <%SpaceRequiredText%>"

ChooseComponents,Title
"Egyedi telepítés"

CopyFiles,CancelButton
"<%Cancel%>"

CopyFiles,Caption
"<%GroupBeingInstalledText%>"

CopyFiles,Message
"<%Status%>"

CopyFiles,ProgressValue
"<%InstallPercentComplete%>"

CopyFiles,Title
"Állományok másolása"

CustomBlankPane1,BackButton
"< <%Back%>"

CustomBlankPane1,CancelButton
"<%Cancel%>"

CustomBlankPane1,NextButton
"<%Next%> >"

CustomBlankPane1,Title
"A fejléc jön ide."

CustomTextPane1,BackButton
"< <%Back%>"

CustomTextPane1,CancelButton
"<%Cancel%>"

CustomTextPane1,Caption
"Leírás"

CustomTextPane1,Message
"Üzenet"

CustomTextPane1,NextButton
"<%Next%> >"

CustomTextPane1,Title
"Cím"

CustomTextPane2,BackButton
"< <%Back%>"

CustomTextPane2,CancelButton
"<%Cancel%>"

CustomTextPane2,Caption
"Fejléc"

CustomTextPane2,NextButton
"<%Next%> >"

CustomTextPane2,Text
"Szöveg kerül ide."

CustomTextPane2,Title
"<%AppName%> Telepítés"

CustomTextPane3,BackButton
"< <%Back%>"

CustomTextPane3,CancelButton
"<%No%>"

CustomTextPane3,Caption
"Fejléc"

CustomTextPane3,Message
"Üzenet"

CustomTextPane3,NextButton
"<%Yes%>"

CustomTextPane3,Text
"Szöveg kerül ide."

CustomTextPane3,Title
"Cím"

License,AcceptCheck
"Elfogadom ezt a licensz megállapodás feltételeit."

License,BackButton
"< <%Back%>"

License,CancelButton
"<%No%>"

License,Caption
"Kérem olvassa el a következ\u0151 Licensz megállapodást.  Nyomja le a PAGE DOWN billenty\u0171t, hogy lássa a megállapodás további részét."

License,Message
"Elfogadja a fenti Licensz megállapodás minden feltételét?  Ha Nem-et választ, akkor a telepítés befejez\u0151dik.  A <%AppName%> telepítéséhez el kell fogadnia ezt a megállapodást."

License,NextButton
"<%Yes%>"

License,Text
"Rakja ide a licensz megállapodását."

License,Title
"Licensz elfogadása"

Readme,BackButton
"< <%Back%>"

Readme,CancelButton
"<%Cancel%>"

Readme,NextButton
"<%Next%> >"

Readme,Text
"Rakja ide az olvassa el információit."

Readme,Title
"Olvassa el információk"

SelectDestination,BackButton
"< <%Back%>"

SelectDestination,BrowseButton
"<%Browse%>"

SelectDestination,CancelButton
"<%Cancel%>"

SelectDestination,Caption
"A telepít\u0151 a <%AppName%> programot a következ\u0151 könyvtárba telepíti.


 Ahhoz, hogy ebbe könyvtárba kerüljön kattintson a <%Next%> gombra Ahhoz, hogy más könyvtárba kerüljön kattintson a <%Browse%> gombra.


	 A <%Cancel%> választásával kiléphet a <%AppName%> program telepítéséb\u0151l."

SelectDestination,DestinationLabel
"Célkönyvtár"

SelectDestination,NextButton
"<%Next%> >"

SelectDestination,Title
"Válassza ki a célkönyvtárat"

SelectProgramFolder,AllUsersCheckbutton
"Létrehozza a program mappát az összes felhasználónak?"

SelectProgramFolder,BackButton
"< <%Back%>"

SelectProgramFolder,CancelButton
"<%Cancel%>"

SelectProgramFolder,Caption
"A telepít\u0151 a program ikonokat a lentebb listázott Program mappához fogja hozzáadni.  Megváltoztathatja az új mappa nevét, vagy kiválaszthat egy már létez\u0151t a listáról.  Kattintson a <%Next%> gombra a folytatáshoz."

SelectProgramFolder,FolderListLabel
"Létez\u0151 mappák:"

SelectProgramFolder,NextButton
"<%Next%> >"

SelectProgramFolder,ProgramFolderLabel
"Program mappa:"

SelectProgramFolder,Title
"Program mappa kiválasztás"

Setup,Caption
"A telepít\u0151 el\u0151készíti az InstallJammer Varázslót, amely keresztülvezeti Önt a telepítés folyamatán.  Kérem várjon!"

Setup,Title
"Telepítés"

SetupComplete,BackButton
"< <%Back%>"

SetupComplete,CancelButton
"<%Cancel%>"

SetupComplete,Caption
"A telepít\u0151 befejezte az <%AppName%> program telepítését a számítógépére."

SetupComplete,NextButton
"<%Finish%>"

SetupComplete,Text
"Kattintson a <%Finish%> gombra a telepítés befejezéséhez."

SetupComplete,Title
"Telepítés befejez\u0151dött"

SetupType,BackButton
"< <%Back%>"

SetupType,CancelButton
"<%Cancel%>"

SetupType,Caption
"Válassza ki a kívánt telepítési típust, majd kattintson a <%Next%> gombra!"

SetupType,NextButton
"<%Next%> >"

SetupType,Title
"Telepítés típusa"

StartCopyingFiles,BackButton
"< <%Back%>"

StartCopyingFiles,CancelButton
"<%Cancel%>"

StartCopyingFiles,Caption
"A telepít\u0151nek elég információja van ahhoz, hogy a program állományait elkezdje másolni.  Ha meg akarja nézni vagy változtatni a beállításokat, akkor kattintson a <%Back%> gombra.  Ha elégedett a beállításokkal, akkor kattintson a <%Next%> gombra, hogy elkezd\u0151djön a fájlok másolása.  

Jelenlegi beállítások:"

StartCopyingFiles,NextButton
"<%Next%> >"

StartCopyingFiles,Text
"Telepítési könyvtár:
 	<%InstallDir%>

 Telepítés típusa:

 	<%InstallType%>"

StartCopyingFiles,Title
"Állományok másolásának elkezdése"

Uninstall,BackButton
"< <%Back%>"

Uninstall,CancelButton
"<%Cancel%>"

Uninstall,Caption
"<%GroupBeingUninstalledText%>"

Uninstall,Message
"<%Status%>"

Uninstall,NextButton
"<%Next%> >"

Uninstall,ProgressValue
"<%UninstallPercentComplete%>"

Uninstall,Title
"<%AppName%> eltávolítása"

UninstallComplete,Caption
"Az eltávolítás sikeresen befejez\u0151dött."

UninstallComplete,FinishButton
"<%Finish%>"

UninstallComplete,Title
"Eltávolítás befejez\u0151dött"

UninstallDetails,Caption
"A következ\u0151 hibák léptek fel az eltávolítás alatt:"

UninstallDetails,Errors
"<%Errors%>"

UninstallDetails,FinishButton
"<%Finish%>"

UninstallDetails,Title
"Eltávolítás részletei"

UserInformation,BackButton
"< <%Back%>"

UserInformation,CancelButton
"<%Cancel%>"

UserInformation,Caption
"Kérem írja be a nevét és a munkahelyének nevét."

UserInformation,CompanyLabel
"Cég:"

UserInformation,NameLabel
"Felhasználó neve:"

UserInformation,NextButton
"<%Next%> >"

UserInformation,Title
"Felhasználói információk"

Welcome,BackButton
"< <%Back%>"

Welcome,CancelButton
"<%Cancel%>"

Welcome,Caption
"Üdvözli a <%AppName%> telepít\u0151je.  Ez program a <%AppName%> programot fogja telepíteni a számítógépére."

Welcome,Message
"Er\u0151sen javasolt, hogy lépjen ki minden futó Windows programból.  Kattintson a <%Next%> gombra, hogy folytassa a telepítést.

 FIGYELMEZTETÉS: Ezt a programot szerz\u0151i jogok és nemzetközi szerz\u0151dések védik.

Ezen program nem engedélyezett gyártása és forgalmazása polgári büntetést eredményezhet és a törvény teljes erejével sújt le."

Welcome,NextButton
"<%Next%> >"

Welcome,Title
"Üdvözl\u0151 képerny\u0151"
