Background,Text
"<%AppName%>"

Background,Title
"<%AppName%> Setup"

ChooseComponents,BackButton
"< <%Back%>"

ChooseComponents,CancelButton
"<%Cancel%>"

ChooseComponents,Caption
"Selecteer de componenten die u wilt installeren en deselecteer de componenten die u niet wilt installeren."

ChooseComponents,ComponentLabel
"Componenten"

ChooseComponents,DescriptionLabel
"Omschrijving"

ChooseComponents,NextButton
"<%Next%> >"

ChooseComponents,SpaceRequiredLabel
"Benodigde ruimte: <%SpaceRequiredText%>"

ChooseComponents,Title
"Custom Setup"

CopyFiles,CancelButton
"<%Cancel%>"

CopyFiles,Caption
"<%GroupBeingInstalledText%>"

CopyFiles,Message
"<%Status%>"

CopyFiles,ProgressValue
"<%InstallPercentComplete%>"

CopyFiles,Title
"Bestanden kopiëren "

CustomBlankPane1,BackButton
"< <%Back%>"

CustomBlankPane1,CancelButton
"<%Cancel%>"

CustomBlankPane1,NextButton
"<%Next%> >"

CustomBlankPane1,Title
"<%AppName%> Setup"

CustomTextPane1,BackButton
"< <%Back%>"

CustomTextPane1,CancelButton
"<%Cancel%>"

CustomTextPane1,Caption
"Bijschrift"

CustomTextPane1,Message
"Bericht"

CustomTextPane1,NextButton
"<%Next%> >"

CustomTextPane1,Title
"Titel"

CustomTextPane2,BackButton
"< <%Back%>"

CustomTextPane2,CancelButton
"<%Cancel%>"

CustomTextPane2,Caption
"Bijschrift"

CustomTextPane2,NextButton
"<%Next%> >"

CustomTextPane2,Text
"Tekst gaat hier."

CustomTextPane2,Title
"<%AppName%> Setup"

CustomTextPane3,BackButton
"< <%Back%>"

CustomTextPane3,CancelButton
"<%No%>"

CustomTextPane3,Caption
"Bijschrift"

CustomTextPane3,Message
"Bericht"

CustomTextPane3,NextButton
"<%Yes%>"

CustomTextPane3,Text
"Tekst gaat hier."

CustomTextPane3,Title
"Titel"

License,AcceptCheck
"Ik ga akkoord met de licentie overeenkomst."

License,BackButton
"< <%Back%>"

License,CancelButton
"Stop Installatie"

License,Caption
"Lees de licentie overeenkomst aandachtig.  Gebruik de PAGE DOWN toets om de rest van de overeenkomst te zien."

License,Message
"Gaat u akkoord met de licentie overeenkomst?  Als u Nee kiest zal de installatie worden afgebroken.  Om <%AppName%> te installeren, moet u akkoord gaan."

License,NextButton
"Ja"

License,Text
"De licentie overeenkomst kunt u hier plaatsen."

License,Title
"Licentie Overeenkomst"

Readme,BackButton
"< <%Back%>"

Readme,CancelButton
"<%Cancel%>"

Readme,NextButton
"<%Next%> >"

Readme,Text
"Plaats uw readme informatie hier."

Readme,Title
"Readme Informatie"

SelectDestination,BackButton
"< <%Back%>"

SelectDestination,BrowseButton
"<%Browse%>"

SelectDestination,CancelButton
"<%Cancel%>"

SelectDestination,Caption
"Dit installatie programma zal <%AppName%> in de onderstaande map installeren.


 Als u de installatie locatie wilt wijzigen klikt u op 'Selecteer map' en selecteert u een nieuwe locatie.
 Om verder te gaan met het installatieproces klikt u op Volgende."

SelectDestination,DestinationLabel
"Installatie map"

SelectDestination,NextButton
"<%Next%> >"

SelectDestination,Title
"Kies de installatie map"

SelectProgramFolder,AllUsersCheckbutton
"Maak programma map voor alle gebruikers"

SelectProgramFolder,BackButton
"< <%Back%>"

SelectProgramFolder,CancelButton
"<%Cancel%>"

SelectProgramFolder,Caption
"Het installatie programma zal de programma iconen toevoegen aan de onderstaande Programma map.  U kunt een nieuwe map aanmaken of een bestaande map selecteren uit de lijst.  Klik op Volgende om door te gaan."

SelectProgramFolder,FolderListLabel
"Huidige mappen:"

SelectProgramFolder,NextButton
"<%Next%> >"

SelectProgramFolder,ProgramFolderLabel
"Programma map:"

SelectProgramFolder,Title
"Selecteer Programma Map"

Setup,Caption
"Setup is de wizard aan het voorbereiden die u door de rest van het proces begeleid.  Een ogenblik geduld."

Setup,Title
"Setup"

SetupComplete,BackButton
"< <%Back%>"

SetupComplete,CancelButton
"<%Cancel%>"

SetupComplete,Caption
"Setup is klaar met het installeren van <%AppName%> op uw computer."

SetupComplete,NextButton
"<%Finish%>"

SetupComplete,Text
"Klik op <%Finish%> om de installatie af te ronden."

SetupComplete,Title
"Setup Afgerond"

SetupType,BackButton
"< <%Back%>"

SetupType,CancelButton
"<%Cancel%>"

SetupType,Caption
"Kies het type setup dat u prefereerd, klik daarna op Volgende."

SetupType,NextButton
"<%Next%> >"

SetupType,Title
"Setup Type"

StartCopyingFiles,BackButton
"< <%Back%>"

StartCopyingFiles,CancelButton
"<%Cancel%>"

StartCopyingFiles,Caption
"Het installatie programma heeft genoeg informatie om het kopiëren te starten.  Als u de instellingen wilt bekijken of wijzigen kunt op <%Back%> klikken.  Als u tevreden bent met de instellingen klikt u op <%Next%> om het kopiëren te starten.  

Huidige instellingen:"

StartCopyingFiles,NextButton
"<%Next%> >"

StartCopyingFiles,Text
"Installatie map:
 	<%InstallDir%>

 Setup type:
 	<%InstallType%>"

StartCopyingFiles,Title
"Start Kopiëren Bestanden"

Uninstall,BackButton
"< <%Back%>"

Uninstall,CancelButton
"<%Cancel%>"

Uninstall,Caption
"<%GroupBeingUninstalledText%>"

Uninstall,Message
"<%Status%>"

Uninstall,NextButton
"<%Next%> >"

Uninstall,ProgressValue
"<%UninstallPercentComplete%>"

Uninstall,Title
"<%AppName%> deïnstalleren"

UninstallComplete,Caption
"Deïnstallatie succesvol afgerond."

UninstallComplete,FinishButton
"<%Finish%>"

UninstallComplete,Title
"Deïnstallatie Afgerond"

UninstallDetails,Caption
"De volgende fouten hebben zicht voorgedaan tijdens de deïnstallatie:"

UninstallDetails,Errors
"<%Errors%>"

UninstallDetails,FinishButton
"<%Finish%>"

UninstallDetails,Title
"Deïnstallatie Details"

UserInformation,BackButton
"< <%Back%>"

UserInformation,CancelButton
"<%Cancel%>"

UserInformation,Caption
"Vul uw naam en uw bedrijfsnaam in."

UserInformation,CompanyLabel
"Bedrijfsnaam:"

UserInformation,NameLabel
"Naam:"

UserInformation,NextButton
"<%Next%> >"

UserInformation,Title
"Gebruikers Informatie"

Welcome,BackButton
"< <%Back%>"

Welcome,CancelButton
"<%Cancel%>"

Welcome,Caption
"Welkom bij het <%AppName%> installatie programma.  Dit programma zal <%AppName%> op uw computer installeren."

Welcome,Message
"Het is aan te raden alle overige applicaties te sluiten alvorens verder te gaan met deze installatie.

Klik op <%Next%> om verder te gaan of op <%Cancel%> om deze installatie af te breken"

Welcome,NextButton
"<%Next%> >"

Welcome,Title
"Welkomst Scherm"
