Background,Text
"<%AppName%>"

Background,Title
"Instalação do <%AppName%>"

ChooseComponents,BackButton
"< <%Back%>"

ChooseComponents,CancelButton
"<%Cancel%>"

ChooseComponents,Caption
"Selecione os componentes que você quer instalar e deselecione os componentes que você não quer instalar."

ChooseComponents,ComponentLabel
"Componentes"

ChooseComponents,DescriptionLabel
"Descrição"

ChooseComponents,NextButton
"<%Next%> >"

ChooseComponents,SpaceRequiredLabel
"Espaço necessário: <%SpaceRequiredText%>"

ChooseComponents,Title
"Instalação Customizada"

CopyFiles,CancelButton
"<%Cancel%>"

CopyFiles,Caption
"<%GroupBeingInstalledText%>"

CopyFiles,Message
"<%Status%>"

CopyFiles,ProgressValue
"<%InstallPercentComplete%>"

CopyFiles,Title
"Copiando arquivos"

CustomBlankPane1,BackButton
"< <%Back%>"

CustomBlankPane1,CancelButton
"<%Cancel%>"

CustomBlankPane1,NextButton
"<%Next%> >"

CustomBlankPane1,Title
"Instalação do <%AppName%>"

CustomTextPane1,BackButton
"< <%Back%>"

CustomTextPane1,CancelButton
"<%Cancel%>"

CustomTextPane1,Caption
"Caption"

CustomTextPane1,Message
"Mensagem"

CustomTextPane1,NextButton
"<%Next%> >"

CustomTextPane1,Title
"Título"

CustomTextPane2,BackButton
"< <%Back%>"

CustomTextPane2,CancelButton
"<%Cancel%>"

CustomTextPane2,Caption
"Caption"

CustomTextPane2,NextButton
"<%Next%> >"

CustomTextPane2,Text
"Texto aparecerá aqui."

CustomTextPane2,Title
"Instalação do <%AppName%>"

CustomTextPane3,BackButton
"< <%Back%>"

CustomTextPane3,CancelButton
"<%No%>"

CustomTextPane3,Caption
"Caption"

CustomTextPane3,Message
"Mensagem"

CustomTextPane3,NextButton
"<%Yes%>"

CustomTextPane3,Text
"Texto aparecerá aqui."

CustomTextPane3,Title
"Título"

License,AcceptCheck
"Eu aceito todos os termos desta Licença."

License,BackButton
"< <%Back%>"

License,CancelButton
"Não"

License,Caption
"Por favor, leia a Concordância com a Licença.  Pressione PAGEDOWN para visualizar o resto da licença."

License,Message
"Você aceita todos os termos da Licença?  Se você escolher Não, A instalação será Cancelada.  Para instalar <%AppName%>, você precisa aceitar todos os termos da Licença."

License,NextButton
"Sim"

License,Text
"Coloque a sua Concordância com a Licença aqui."

License,Title
"Concordância com a Licença"

Readme,BackButton
"< <%Back%>"

Readme,CancelButton
"<%Cancel%>"

Readme,NextButton
"<%Next%> >"

Readme,Text
"Coloque as informações do seu Readme aqui."

Readme,Title
"Informação do Readme"

SelectDestination,BackButton
"< <%Back%>"

SelectDestination,BrowseButton
"<%Browse%>"

SelectDestination,CancelButton
"<%Cancel%>"

SelectDestination,Caption
"O Instalador irá instalar <%AppName%> Na seguinte pasta.

Para instalar nesta pasta, clique em Próximo.

Para instalar em uma pasta diferente, clique Navegar e selecione outra pasta.

Você pode cancelar a Instalação do <%AppName%> clicando em Cancelar e o Instalador será finalizado."

SelectDestination,DestinationLabel
"Pasta de destino"

SelectDestination,NextButton
"<%Next%> >"

SelectDestination,Title
"Selecione a localização de destino"

SelectProgramFolder,AllUsersCheckbutton
"Criar uma pasta de programa para todos os usuários"

SelectProgramFolder,BackButton
"< <%Back%>"

SelectProgramFolder,CancelButton
"<%Cancel%>"

SelectProgramFolder,Caption
"Setup will add the program icons to the Program Folder listed below.  You may type a new folder name or select from the existing folders list.  Click Next to continue."

SelectProgramFolder,FolderListLabel
"Pastas Existentes:"

SelectProgramFolder,NextButton
"<%Next%> >"

SelectProgramFolder,ProgramFolderLabel
"Pasta de Programas:"

SelectProgramFolder,Title
"Selecionar a pasta de Programas"

Setup,Caption
"A Instalação está preparando o Assistente do InstallJammer que irá te guiar através do processo de instalação.  Por favor aguarde."

Setup,Title
"Instalação"

SetupComplete,BackButton
"< <%Back%>"

SetupComplete,CancelButton
"<%Cancel%>"

SetupComplete,Caption
"O Instalador concluiu a instalação do <%AppName%> em seu computador."

SetupComplete,NextButton
"<%Finish%>"

SetupComplete,Text
"Clique em Concluir para finalizar a Instalação."

SetupComplete,Title
"Instalação Concluída"

SetupType,BackButton
"< <%Back%>"

SetupType,CancelButton
"<%Cancel%>"

SetupType,Caption
"Click the type of Setup you prefer, then click Next."

SetupType,NextButton
"<%Next%> >"

SetupType,Title
"Setup Type"

StartCopyingFiles,BackButton
"< <%Back%>"

StartCopyingFiles,CancelButton
"<%Cancel%>"

StartCopyingFiles,Caption
"Setup has enough information to start copying the program files.  If you want to review or change any settings, click Back.  If you are satisfied with the settings, click Next to begin copying files.  

Current Settings:"

StartCopyingFiles,NextButton
"<%Next%> >"

StartCopyingFiles,Text
"Install Directory:
 	<%InstallDir%>

 Setup Type:
 	<%InstallType%>"

StartCopyingFiles,Title
"Start Copying Files"

Uninstall,BackButton
"< <%Back%>"

Uninstall,CancelButton
"<%Cancel%>"

Uninstall,Caption
"<%GroupBeingUninstalledText%>"

Uninstall,Message
"<%Status%>"

Uninstall,NextButton
"<%Next%> >"

Uninstall,ProgressValue
"<%UninstallPercentComplete%>"

Uninstall,Title
"Desinstalar <%AppName%>"

UninstallComplete,Caption
"Desinstalação Concluída com Sucesso."

UninstallComplete,FinishButton
"<%Finish%>"

UninstallComplete,Title
"Desinstalação Concluída"

UninstallDetails,Caption
"Os seguintes erros ocorreram durante a deinstalação:"

UninstallDetails,Errors
"<%Errors%>"

UninstallDetails,FinishButton
"<%Finish%>"

UninstallDetails,Title
"Detalhes de Desintalação"

UserInformation,BackButton
"< <%Back%>"

UserInformation,CancelButton
"<%Cancel%>"

UserInformation,Caption
"Digite seu nome e a empresa onde você trabalha."

UserInformation,CompanyLabel
"Empresa:"

UserInformation,NameLabel
"Nome:"

UserInformation,NextButton
"<%Next%> >"

UserInformation,Title
"Informação do Usuário"

Welcome,BackButton
"< <%Back%>"

Welcome,CancelButton
"<%Cancel%>"

Welcome,Caption
"Bem vido ao programa de Instalação do <%AppName%>.  Este programa irá instalar <%AppName%> em seu computador."

Welcome,Message
"É fortemente recomendado que você feche todos os programas do Windows que você esteja executando.  Clique em Próximo para continuar o programa de Instalação.

Advertência: Este programa é protegido por leis de Copyright e tratados Internacionais.  


 A cópia não autorizada ou a distribuição deste programa, or qualquer parte deste, poderá resultar em severas penalidades cívis e criminais e será processado dentro da leis aplicáveis."

Welcome,NextButton
"<%Next%> >"

Welcome,Title
"Tela de Boas Vindas"
