## $Id$
##
## BEGIN LICENSE BLOCK
##
## Copyright (C) 2002  Damon Courtney
## 
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## version 2 as published by the Free Software Foundation.
## 
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License version 2 for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the
##     Free Software Foundation, Inc.
##     51 Franklin Street, Fifth Floor
##     Boston, MA  02110-1301, USA.
##
## END LICENSE BLOCK

Action LocateJavaRuntime "Locate Java Runtime"

Property FindAllVersions boolean "Find All Versions" "No"
Help FindAllVersions "If this property is true, the action will not stop\
    searching when it finds a matching Java version.  It will instead keep\
    looking until it has found all versions that match"

Property SearchPath text "Search Path" "Default Search Path\;Prompt User"
Help SearchPath "A list of paths to search separated by ;.
Default Search Path tells InstallJammer to look in the most common places.
Prompt User will ask the user if all else fails."

Property MinimumVersion short "Minimum Version"
Help MinimumVersion "The lowest version of Java that is acceptable"

Property MaximumVersion short "Maximum Version"
Help MinimumVersion "The highest version of Java that is acceptable"

Property RequireJDK boolean "Require JDK" "No"
Help RequireJDK "This property tells InstallJammer to look specifically for\
    an installed JDK and not just a JRE.  This is indicated by the presence\
    of the javac binary."

Property ValidVersions short "Valid Versions" ""
Help ValidVersions "A specific list of versions separated by ; that are\
    acceptable"

Text PromptMessage
Text StatusMessage

Script {
    $obj properties props -subst 1

    set args {}
    lappend args -all $props(FindAllVersions)
    lappend args -searchpath $props(SearchPath)
    lappend args -requirejdk $props(RequireJDK)
    lappend args -minversion $props(MinimumVersion)
    lappend args -maxversion $props(MaximumVersion)
    lappend args -validversions $props(ValidVersions)
    lappend args -promptmessage [$obj get PromptMessage]
    lappend args -statusmessage [$obj get StatusMessage]

    ::InstallAPI::LocateJavaRuntime {*}$args
}
