## $Id$
##
## BEGIN LICENSE BLOCK
##
## Copyright (C) 2002  Damon Courtney
## 
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## version 2 as published by the Free Software Foundation.
## 
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License version 2 for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the
##     Free Software Foundation, Inc.
##     51 Franklin Street, Fifth Floor
##     Boston, MA  02110-1301, USA.
##
## END LICENSE BLOCK

Action FetchURL "Fetch URL"

Property ProxyHost short "Proxy Host"
Help ProxyHost "The hostname to use as a proxy server if required"

Property ProxyPort short "Proxy Port"
Help ProxyPort "The port to use on the proxy server if required"

Property SaveTo choice "Save To" "file" {file virtualtext}
Help SaveTo "Whether to save the URL to a file or virtual text"

Property Target installedfile "Target" "<%Temp%>"
Help Target "The name of the file or virtual text to store the URL contents in"

Property Timeout short "Timeout" "10000"
Help Timeout "The amount of time to wait for a connection (in milliseconds)"

Property URL shorttext "URL"
Help URL "The full URL path to fetch"

Property ProgressVirtualText short "Progress Virtual Text"
Help ProgressVirtualText "The name of a virtual text variable to track the\
                        progress of the download"

proc ::InstallJammer::actions::FetchURL { obj } {
    $obj properties props -subst 1

    lappend args -url $props(URL)
    if {$props(Timeout) ne ""} { lappend args -timeout $props(Timeout) }
    if {$props(ProxyHost) ne ""} { lappend args -proxyhost $props(ProxyHost) }
    if {$props(ProxyPort) ne ""} { lappend args -proxyport $props(ProxyPort) }
    if {$props(ProgressVirtualText) ne ""} {
        lappend args -progressvirtualtext $props(ProgressVirtualText)
    }

    if {$props(SaveTo) eq "file"} {
        lappend args -file $props(Target)
    } else {
        lappend args -virtualtext $props(Target)
    }

    eval ::InstallAPI::FetchURL $args
}
