ChooseComponents,BackButton
"< <%Back%>"

ChooseComponents,CancelButton
"<%Cancel%>"

ChooseComponents,Caption
"Wählen Sie die zu installierenden Komponenten aus und deselektieren Sie die Komponenten, die Sie nicht installieren möchten."

ChooseComponents,DescriptionLabel
"Beschreibung"

ChooseComponents,Message
"<%SpaceRequiredText%> an Plattenplatz benötigt"

ChooseComponents,NextButton
"<%Next%> >"

ChooseComponents,Subtitle
"Wählen Sie die zu installierenden Komponenten aus."

ChooseComponents,Title
"Auswahl Komponenten"

CopyFiles,BackButton
"< <%Back%>"

CopyFiles,CancelButton
"<%Cancel%>"

CopyFiles,Caption
"Bitte warten Sie, während Setup <%AppName%> auf Ihrem Computer installiert."

CopyFiles,FileLabel
"<%Status%>"

CopyFiles,Message
""

CopyFiles,NextButton
"<%Next%> >"

CopyFiles,ProgressValue
"<%InstallPercentComplete%>"

CopyFiles,Subtitle
"Installiere <%AppName%>"

CopyFiles,Title
"Installation"

CustomBlankPane1,BackButton
"< <%Back%>"

CustomBlankPane1,CancelButton
"<%Cancel%>"

CustomBlankPane1,Caption
"Überschrift kommt hier hin."

CustomBlankPane1,Message
"Meldung kommt hier hin."

CustomBlankPane1,NextButton
"<%Next%> >"

CustomBlankPane2,BackButton
"< <%Back%>"

CustomBlankPane2,CancelButton
"<%Cancel%>"

CustomBlankPane2,Caption
"Überschrift"

CustomBlankPane2,Message
"Meldung"

CustomBlankPane2,NextButton
"<%Next%> >"

CustomBlankPane2,Subtitle
"Untertitel"

CustomBlankPane2,Title
"Titel"

CustomTextPane1,BackButton
"< <%Back%>"

CustomTextPane1,CancelButton
"<%Cancel%>"

CustomTextPane1,Caption
"Untertitel"

CustomTextPane1,Message
"Meldung"

CustomTextPane1,NextButton
"<%Next%> >"

CustomTextPane1,Subtitle
"Untertitel"

CustomTextPane1,Text
"Ihr benutzerdefinierter Text kommt hier hin."

CustomTextPane1,Title
"Titel"

License,AcceptRadiobutton
"Ich akzeptiere die Lizenzbestimmungen."

License,BackButton
"< <%Back%>"

License,CancelButton
"<%No%>"

License,DeclineRadiobutton
"Ich akzeptiere nicht die Lizenzbestimmungen."

License,NextButton
"<%Yes%>"

License,Subtitle
"Bitte lesen Sie die folgenden Lizenzbestimmungen aufmerksam."

License,Title
"Lizenzbestimmungen"

Readme,BackButton
"< <%Back%>"

Readme,CancelButton
"<%Cancel%>"

Readme,Caption
""

Readme,Message
""

Readme,NextButton
"<%Next%> >"

Readme,Subtitle
"Liesmich Informationen für <%AppName%>"

Readme,Text
""

Readme,Title
"Liesmich Informationen"

SelectDestination,BackButton
"< <%Back%>"

SelectDestination,BrowseButton
"<%Browse%>"

SelectDestination,BrowseText
"Um Fortzufahren, klicken Sie auf Weiter.  Wenn Sie ein anderes Verzeichnis verwenden möchten, klicken Sie auf Durchsuchen."

SelectDestination,CancelButton
"<%Cancel%>"

SelectDestination,Caption
"Setup wird <%AppName%> in das folgende Verzeichnis installieren.  

Klicken Sie auf Weiter, wenn dieses Verzeichnis verwendet werden soll.  Um ein anderes Verzeichnis auszuwählen, klicken Sie auf Durchsuchen und wählen ein anderes aus."

SelectDestination,DestinationLabel
"Zielordner"

SelectDestination,Message
""

SelectDestination,NextButton
"<%Next%> >"

SelectDestination,Subtitle
"Wohin soll <%AppName%> installiert werden?"

SelectDestination,Title
"Auswahl Installationsziel"

SelectProgramFolder,AllUsersCheckbutton
"Erstelle Programmordner für alle Benutzer"

SelectProgramFolder,BackButton
"< <%Back%>"

SelectProgramFolder,CancelButton
"<%Cancel%>"

SelectProgramFolder,Caption
"Setup wird die Programmsymbole zum unten aufgeführten Programmordner hinzufügen.  Sie können einen neuen Ordnernamen eingeben oder einen von der von der existierenden Ordnerliste auswählen.  Klicken Sie auf Weiter um Fortzufahren."

SelectProgramFolder,FolderListLabel
"Vorhandene Ordner:"

SelectProgramFolder,Message
""

SelectProgramFolder,NextButton
"<%Next%> >"

SelectProgramFolder,ProgramFolderLabel
"Programmordner:"

SelectProgramFolder,Subtitle
"Bitte wählen Sie einen Programmordner."

SelectProgramFolder,Title
"Auswahl Programmordner"

SetupComplete,BackButton
"< <%Back%>"

SetupComplete,CancelButton
"<%Cancel%>"

SetupComplete,Caption
"Installation Abgeschlossen"

SetupComplete,Message
"InstallJammer hat <%AppName%> erfolgreich installiert.  Klicken Sie auf Beenden, um den Assistenten zu verlassen."

SetupComplete,NextButton
"<%Finish%>"

SetupType,BackButton
"< <%Back%>"

SetupType,CancelButton
"<%Cancel%>"

SetupType,Caption
"Klicken Sie auf die bevorzugte Art des Setup."

SetupType,DescriptionLabel
"Beschreibung"

SetupType,Message
""

SetupType,NextButton
"<%Next%> >"

SetupType,Subtitle
"Wählen Sie die Art des Setup, welche am Besten Ihren Anforderungen entspricht."

SetupType,Title
"Setup Art"

StartCopyingFiles,BackButton
"< <%Back%>"

StartCopyingFiles,CancelButton
"<%Cancel%>"

StartCopyingFiles,Caption
"Setup hat genug Informationen, um die Programmdateien zu kopieren.  Wenn Sie die Einstellungen überprüfen oder ändern möchten, klicken Sie auf Zurück.  Wenn Sie mit den Einstellungen zufrieden sind, klicken Sie auf Weiter, um mit dem Kopieren der Dateien zu beginnen."

StartCopyingFiles,Message
""

StartCopyingFiles,NextButton
"<%Next%> >"

StartCopyingFiles,Subtitle
"Überprüfen Sie die Einstellungen, bevor die Dateien kopiert werden."

StartCopyingFiles,Text
"Installationsverzeichnis:
 <%InstallDir%>

 Setup Art:
 <%InstallType%>"

StartCopyingFiles,Title
"Kopieren der Dateien"

Uninstall,BackButton
"< <%Back%>"

Uninstall,CancelButton
"<%Cancel%>"

Uninstall,Caption
"<%GroupBeingUninstalledText%>"

Uninstall,FileValue
"<%Status%>"

Uninstall,Message
""

Uninstall,NextButton
"<%Next%> >"

Uninstall,ProgressValue
"<%UninstallPercentComplete%>"

Uninstall,Subtitle
"Deinstalliere <%AppName%>"

Uninstall,Title
"Deinstallation"

UninstallComplete,BackButton
"< <%Back%>"

UninstallComplete,CancelButton
"<%Cancel%>"

UninstallComplete,Caption
"Deinstallation Abgeschlossen"

UninstallComplete,Message
"<%AppName%> wurde von Ihrem System entfernt."

UninstallComplete,NextButton
"<%Finish%>"

UninstallDetails,BackButton
"< <%Back%>"

UninstallDetails,CancelButton
"<%Cancel%>"

UninstallDetails,Caption
"Die folgenden Fehler sind beim Löschen aufgetreten:"

UninstallDetails,Message
""

UninstallDetails,NextButton
"<%Next%> >"

UninstallDetails,Subtitle
"Es sind Fehler beim Löschen aufgetreten"

UninstallDetails,Text
"<%Errors%>"

UninstallDetails,Title
"Deinstallation Details"

UserInformation,BackButton
"< <%Back%>"

UserInformation,CancelButton
"<%Cancel%>"

UserInformation,Caption
"Bitte geben Sie Ihren Namen und den Namen der Firma ein, für die Sie arbeiten."

UserInformation,CompanyLabel
"Firma:"

UserInformation,Message
""

UserInformation,NextButton
"<%Next%> >"

UserInformation,Subtitle
"Bitte geben Sie Ihre Informationen ein."

UserInformation,Title
"Benutzer Information"

UserInformation,UserNameLabel
"Benutzername:"

Welcome,BackButton
"< <%Back%>"

Welcome,CancelButton
"<%Cancel%>"

Welcome,Caption
"Willkommen beim InstallJammer Assistenten für <%AppName%>"

Welcome,Message
"Dies wird <%AppName%> Version <%Version%> auf Ihrem Computer installieren.  

Es wird empfohlen, das Sie alle anderen Anwendungen schließen, bevor Sie fortfahren.

Klicken Sie auf Weiter um Fortzufahren oder auf Abbrechen, um das Setup zu beenden."

Welcome,NextButton
"<%Next%> >"
