ChooseComponents,Caption
"Select the components you want to install and deselect the components you do not want to install."

ChooseComponents,DescriptionLabel
"Description"

ChooseComponents,Message
"<%SpaceRequiredText%> of space required"

ChooseComponents,Subtitle
"Select the components setup will install."

ChooseComponents,Title
"Select Components"

CopyFiles,Caption
"Please wait while Setup installs <%AppName%> on your computer."

CopyFiles,FileLabel
"<%Status%>"

CopyFiles,Message
""

CopyFiles,ProgressValue
"<%InstallPercentComplete%>"

CopyFiles,Subtitle
"Installing <%AppName%>"

CopyFiles,Title
"Installing"

CustomBlankPane1,Caption
"Caption goes here."

CustomBlankPane1,Message
"Message goes here."

CustomBlankPane2,Caption
"Caption"

CustomBlankPane2,Message
"Message"

CustomBlankPane2,Subtitle
"Subtitle"

CustomBlankPane2,Title
"Title"

CustomTextPane1,Caption
"Caption"

CustomTextPane1,Message
"Message"

CustomTextPane1,Subtitle
"Subtitle"

CustomTextPane1,Text
"Put your custom text here."

CustomTextPane1,Title
"Title"

InstallForAll,AllUsersText
"Install for all users (requires root)"

InstallForAll,Caption
"Please select whether you would like to install this application only for the current user or for all users on this system."

InstallForAll,CurrentUserText
"Install only for <%Username%>"

InstallForAll,Message
""

InstallForAll,Subtitle
"Choose who you want to install this application for."

InstallForAll,Title
"Install For User"

InstallPassword,Caption
"Please enter a password."

InstallPassword,Message
""

InstallPassword,Subtitle
"This installation requires a password to continue."

InstallPassword,Title
"Install Password"

License,AcceptRadiobutton
"I accept the terms of the license agreement."

License,DeclineRadiobutton
"I do not accept the terms of the license agreement."

License,Subtitle
"Please read the following license agreement carefully."

License,Text
"Put your license agreement here."

License,Title
"License Agreement"

Readme,Caption
""

Readme,Message
""

Readme,Subtitle
"Readme Information for <%AppName%>"

Readme,Text
"Put your readme information here."

Readme,Title
"Readme Information"

SelectDestination,BrowseButton
"<%Browse%>"

SelectDestination,BrowseText
"To continue, click Next.  If you would like to select a different folder, click Browse."

SelectDestination,Caption
"Setup will install <%AppName%> in the following folder.

To install to this folder, click Next.  To install to a different folder, click Browse and select another folder."

SelectDestination,DestinationLabel
"Destination Folder"

SelectDestination,Message
""

SelectDestination,Subtitle
"Where should <%AppName%> be installed?"

SelectDestination,Title
"Choose Destination Location"

SelectProgramFolder,AllUsersCheckbutton
"Create program folder for all users"

SelectProgramFolder,Caption
"Setup will add the program icons to the Program Folder listed below.  You may type a new folder name or select from the existing folders list.  Click Next to continue."

SelectProgramFolder,FolderListLabel
"Exising Folders:"

SelectProgramFolder,Message
""

SelectProgramFolder,ProgramFolderLabel
"Program Folder:"

SelectProgramFolder,Subtitle
"Please select a program folder."

SelectProgramFolder,Title
"Select Program Folder"

SetupComplete,Caption
"InstallJammer Wizard Complete"

SetupComplete,Message
"The InstallJammer Wizard has successfully installed <%AppName%>.  Click Finish to exit the wizard."

SetupComplete,NextButton
"<%Finish%>"

SetupType,Caption
"Click the type of Setup you prefer."

SetupType,DescriptionLabel
"Description"

SetupType,Message
""

SetupType,Subtitle
"Select the setup type that best suits your needs."

SetupType,Title
"Setup Type"

StartCopyingFiles,Caption
"Setup has enough information to start copying the program files.  If you want to review or change any settings, click Back.  If you are satisfied with the settings, click Next to begin copying files."

StartCopyingFiles,Message
""

StartCopyingFiles,Subtitle
"Review settings before copying files"

StartCopyingFiles,Text
"Install Directory:
        <%InstallDir%>

 Setup Type:
        <%InstallType%>"

StartCopyingFiles,Title
"Start Copying Files"

Uninstall,Caption
"<%GroupBeingUninstalledText%>"

Uninstall,FileValue
"<%Status%>"

Uninstall,Message
""

Uninstall,ProgressValue
"<%UninstallPercentComplete%>"

Uninstall,Subtitle
"Uninstalling <%AppName%>"

Uninstall,Title
"Uninstalling"

UninstallComplete,Caption
"Uninstall Complete"

UninstallComplete,Message
"<%AppName%> has been removed from your system."

UninstallDetails,Caption
"The following errors occurred during removal:"

UninstallDetails,Message
""

UninstallDetails,Subtitle
"Errors occurred during removal"

UninstallDetails,Text
"<%Errors%>"

UninstallDetails,Title
"Uninstall Details"

UserInformation,Caption
"Please enter your name and the name of the company for which you work."

UserInformation,CompanyLabel
"Company:"

UserInformation,Message
""

UserInformation,Subtitle
"Please enter your information."

UserInformation,Title
"Customer Information"

UserInformation,UserNameLabel
"User Name:"

Welcome,Caption
"Welcome to the InstallJammer Wizard for <%AppName%>"

Welcome,Message
"This will install <%AppName%> version <%Version%> on your computer.  

It is recommended that you close all other applications before continuing.

Click Next to continue or Cancel to exit Setup."
