ChooseComponents,BackButton
"< <%Back%>"

ChooseComponents,CancelButton
"<%Cancel%>"

ChooseComponents,Caption
"Sélectionner les composants à installer et déselectionner les composants à ne pas installer."

ChooseComponents,DescriptionLabel
"Description"

ChooseComponents,Message
"<%SpaceRequiredText%> d'espace requis"

ChooseComponents,NextButton
"<%Next%> >"

ChooseComponents,Subtitle
"Sélectionnez les composants devant être installés."

ChooseComponents,Title
"Sélectionnez les composants"

CopyFiles,BackButton
"< <%Back%>"

CopyFiles,CancelButton
"<%Cancel%>"

CopyFiles,Caption
"Patientez pendant l'installation de <%AppName%> sur votre ordinateur."

CopyFiles,FileLabel
"<%Status%>"

CopyFiles,Message
""

CopyFiles,NextButton
"<%Next%> >"

CopyFiles,ProgressValue
"<%InstallPercentComplete%>"

CopyFiles,Subtitle
"Installation de <%AppName%>"

CopyFiles,Title
"Installation"

CustomBlankPane1,BackButton
"< <%Back%>"

CustomBlankPane1,CancelButton
"<%Cancel%>"

CustomBlankPane1,Caption
"Saisir la légende ici."

CustomBlankPane1,Message
"Saisir le message ici."

CustomBlankPane1,NextButton
"<%Next%> >"

CustomBlankPane2,BackButton
"< <%Back%>"

CustomBlankPane2,CancelButton
"<%Cancel%>"

CustomBlankPane2,Caption
"Légende"

CustomBlankPane2,Message
"Message"

CustomBlankPane2,NextButton
"<%Next%> >"

CustomBlankPane2,Subtitle
"Sous-titre"

CustomBlankPane2,Title
"Titre"

CustomTextPane1,BackButton
"< <%Back%>"

CustomTextPane1,CancelButton
"<%Cancel%>"

CustomTextPane1,Caption
"Légende"

CustomTextPane1,Message
"Message"

CustomTextPane1,NextButton
"<%Next%> >"

CustomTextPane1,Subtitle
"Sous-titre"

CustomTextPane1,Text
"Saisissez votre texte personnalisé ici."

CustomTextPane1,Title
"Titre"

License,AcceptRadiobutton
"J'accepte les termes de cet accord de licence."

License,BackButton
"< <%Back%>"

License,CancelButton
"<%No%>"

License,DeclineRadiobutton
"Je n'accepte pas les termes de cet accord de licence."

License,NextButton
"<%Yes%>"

License,Subtitle
"Veuillez lire attentivement l'accord de licence suivant SVP."

License,Title
"Accord de licence"

Readme,BackButton
"< <%Back%>"

Readme,CancelButton
"<%Cancel%>"

Readme,Caption
""

Readme,Message
""

Readme,NextButton
"<%Next%> >"

Readme,Subtitle
"Readme pour <%AppName%>"

Readme,Text
""

Readme,Title
"Readme"

SelectDestination,BackButton
"< <%Back%>"

SelectDestination,BrowseButton
"<%Browse%>"

SelectDestination,BrowseText
"Pour continuer, cliquez sur SUIVANT.  Pour sélectionner un répertoire différent, cliquez sur PARCOURIR."

SelectDestination,CancelButton
"<%Cancel%>"

SelectDestination,Caption
"L'installation de <%AppName%> s'effectuera dans le répertoire suivant.

Pour installer dans ce répertoire, cliquez sur le bouton SUIVANT.

Pour installer dans un autre répertoire, cliquez sur le bouton PARCOURIR et sélectionnez un autre répertoire."

SelectDestination,DestinationLabel
"Répertoire d'installation"

SelectDestination,Message
""

SelectDestination,NextButton
"<%Next%> >"

SelectDestination,Subtitle
"Où installer <%AppName%> ?"

SelectDestination,Title
"Sélectionnez le répertoire d'installation"

SelectProgramFolder,AllUsersCheckbutton
"Créer le dossier programme pour tous les utilisateurs"

SelectProgramFolder,BackButton
"< <%Back%>"

SelectProgramFolder,CancelButton
"<%Cancel%>"

SelectProgramFolder,Caption
"L'installation ajoutera les icônes de programme au dossier Programme affiché ci-dessous.  Vous pouvez saisir un nouveau nom de dossier ou en sélectionner un dans la liste des dossiers existants.  Cliquez sur SUIVANT pour continuer."

SelectProgramFolder,FolderListLabel
"Dossiers existants :"

SelectProgramFolder,Message
""

SelectProgramFolder,NextButton
"<%Next%> >"

SelectProgramFolder,ProgramFolderLabel
"Dossier Programme:"

SelectProgramFolder,Subtitle
"Sélectionnez un dossier Programme SVP."

SelectProgramFolder,Title
"Sélectionnez le dossier Programme"

SetupComplete,BackButton
"< <%Back%>"

SetupComplete,CancelButton
"<%Cancel%>"

SetupComplete,Caption
"L'assistant InstallJammer est terminé"

SetupComplete,Message
"L'assistant InstallJammer a installé <%AppName%> avec succès.  Cliquez sur TERMINER pour quitter l'assistant."

SetupComplete,NextButton
"<%Finish%>"

SetupType,BackButton
"< <%Back%>"

SetupType,CancelButton
"<%Cancel%>"

SetupType,Caption
"Cliquez sur le type d'installation que vous souhaitez."

SetupType,DescriptionLabel
"Description"

SetupType,Message
""

SetupType,NextButton
"<%Next%> >"

SetupType,Subtitle
"Sélectionnez le type d'installation convenant le mieux à vos besoins."

SetupType,Title
"Type d'installation"

StartCopyingFiles,BackButton
"< <%Back%>"

StartCopyingFiles,CancelButton
"<%Cancel%>"

StartCopyingFiles,Caption
"L'installeur a maintenant assez d'informations pour commencer à copier les fichiers.  Si vous voulez revoir ou modifier le paramétrage, cliquez sur PRECEDENT.  Si vous êtes satisfait du paramétrage, cliquez sur suivant pour commencer à copier les fichiers."

StartCopyingFiles,Message
""

StartCopyingFiles,NextButton
"<%Next%> >"

StartCopyingFiles,Subtitle
"Contrôle du paramétrage avant la copie de fichiers"

StartCopyingFiles,Text
"Répertoire d'installation:
 <%InstallDir%>

 Type d'installation:
 <%InstallType%>"

StartCopyingFiles,Title
"Copie des fichiers"

Uninstall,BackButton
"< <%Back%>"

Uninstall,CancelButton
"<%Cancel%>"

Uninstall,Caption
"<%GroupBeingUninstalledText%>"

Uninstall,FileValue
"<%Status%>"

Uninstall,Message
""

Uninstall,NextButton
"<%Next%> >"

Uninstall,ProgressValue
"<%UninstallPercentComplete%>"

Uninstall,Subtitle
"Désinstallation de <%AppName%>"

Uninstall,Title
"Désinstallation"

UninstallComplete,BackButton
"< <%Back%>"

UninstallComplete,CancelButton
"<%Cancel%>"

UninstallComplete,Caption
"Désinstallation terminée"

UninstallComplete,Message
"<%AppName%> a été désinstallé de votre système."

UninstallComplete,NextButton
"<%Finish%>"

UninstallDetails,BackButton
"< <%Back%>"

UninstallDetails,CancelButton
"<%Cancel%>"

UninstallDetails,Caption
"Les erreurs suivantes sont apparues pendant la désinstallation:"

UninstallDetails,Message
""

UninstallDetails,NextButton
"<%Next%> >"

UninstallDetails,Subtitle
"Des erreurs sont apparues pendant la désinstallation"

UninstallDetails,Text
"<%Errors%>"

UninstallDetails,Title
"Details de la désinstallation"

UserInformation,BackButton
"< <%Back%>"

UserInformation,CancelButton
"<%Cancel%>"

UserInformation,Caption
"Saisissez votre nom et votre société."

UserInformation,CompanyLabel
"Société:"

UserInformation,Message
""

UserInformation,NextButton
"<%Next%> >"

UserInformation,Subtitle
"Saisissez vos informations SVP."

UserInformation,Title
"Information client"

UserInformation,UserNameLabel
"Nom:"

Welcome,BackButton
"< <%Back%>"

Welcome,CancelButton
"<%Cancel%>"

Welcome,Caption
"Bienvenue dans l'assistant d'installation InstallJammer pour <%AppName%>"

Welcome,Message
"Ceci installera <%AppName%> version <%Version%> sur votre ordinateur.  

Il est recommandé de fermer toutes les autres applications avant de continuer.

Cliquez sur SUIVANT pour continuer ou ANNULER pour quitter l'installation."

Welcome,NextButton
"<%Next%> >"
