ChooseComponents,BackButton
"< <%Back%>"

ChooseComponents,CancelButton
"<%Cancel%>"

ChooseComponents,Caption
"Válassza ki azokat a komponenseket, amelyeket fel akar telepíteni, és ne válassza ki azokat, amelyeket nem akar telepíteni."

ChooseComponents,DescriptionLabel
"Leírás"

ChooseComponents,Message
"<%SpaceRequiredText%> szabad hely szükséges"

ChooseComponents,NextButton
"<%Next%> >"

ChooseComponents,Subtitle
"Válassza ki a telepítend\u0151 komponenseket."

ChooseComponents,Title
"Komponensek kiválasztása"

CopyFiles,BackButton
"< <%Back%>"

CopyFiles,CancelButton
"<%Cancel%>"

CopyFiles,Caption
"Kérem várjon, amíg a Telepít\u0151 a <%AppName%> programot feltelepíti a gépére."

CopyFiles,FileLabel
"<%Status%>"

CopyFiles,Message
""

CopyFiles,NextButton
"<%Next%> >"

CopyFiles,ProgressValue
"<%InstallPercentComplete%>"

CopyFiles,Subtitle
"<%AppName%> telepítése"

CopyFiles,Title
"Telepítés"

CustomBlankPane1,BackButton
"< <%Back%>"

CustomBlankPane1,CancelButton
"<%Cancel%>"

CustomBlankPane1,Caption
"A fejléc jön ide."

CustomBlankPane1,Message
"Az üzenet jön ide."

CustomBlankPane1,NextButton
"<%Next%> >"

CustomBlankPane2,BackButton
"< <%Back%>"

CustomBlankPane2,CancelButton
"<%Cancel%>"

CustomBlankPane2,Caption
"Leírás"

CustomBlankPane2,Message
"Üzenet"

CustomBlankPane2,NextButton
"<%Next%> >"

CustomBlankPane2,Subtitle
"Alcím"

CustomBlankPane2,Title
"Cím"

CustomTextPane1,BackButton
"< <%Back%>"

CustomTextPane1,CancelButton
"<%Cancel%>"

CustomTextPane1,Caption
"Leírás"

CustomTextPane1,Message
"Üzenet"

CustomTextPane1,NextButton
"<%Next%> >"

CustomTextPane1,Subtitle
"Alcím"

CustomTextPane1,Text
"A saját szövegedet rakd ide."

CustomTextPane1,Title
"Cím"

InstallPassword,BackButton
"< <%Back%>"

InstallPassword,CancelButton
"<%Cancel%>"

InstallPassword,Caption
"Kérem gépelje be a jelszót."

InstallPassword,Message
""

InstallPassword,NextButton
"<%Next%> >"

InstallPassword,Subtitle
"Ez a telepítés egy jelszót igényel a folytatáshoz."

InstallPassword,Title
"Jelszavas telepítés"

License,AcceptRadiobutton
"Elfogadom a licensz megállapodás feltételeit."

License,BackButton
"< <%Back%>"

License,CancelButton
"<%No%>"

License,DeclineRadiobutton
"Nem fogadom el a licensz megállapodás feltételeit."

License,NextButton
"<%Yes%>"

License,Subtitle
"Kérem olvassa el figyelmesen a következ\u0151 licensz megállapodást."

License,Title
"Licensz elfogadása"

Readme,BackButton
"< <%Back%>"

Readme,CancelButton
"<%Cancel%>"

Readme,Caption
""

Readme,Message
""

Readme,NextButton
"<%Next%> >"

Readme,Subtitle
"Olvassa el információk a <%AppName%> alkalmazáshoz"

Readme,Text
""

Readme,Title
"Olvassa el információk"

SelectDestination,BackButton
"< <%Back%>"

SelectDestination,BrowseButton
"<%Browse%>"

SelectDestination,BrowseText
"A folytatáshoz nyomja meg a <%Next%> gombot.  Ha másik könyvtárat szeretne kiválasztani nyomja meg a <%Browse%> gombot."

SelectDestination,CancelButton
"<%Cancel%>"

SelectDestination,Caption
"A telepít\u0151 a <%AppName%> programot a következ\u0151 könyvtárba telepíti.


 Ahhoz, hogy ebbe könyvtárba kerüljön kattintson a <%Next%> gombra Ahhoz, hogy más könyvtárba kerüljön kattintson a <%Browse%> gombra."

SelectDestination,DestinationLabel
"Cél könyvtár"

SelectDestination,Message
""

SelectDestination,NextButton
"<%Next%> >"

SelectDestination,Subtitle
"Hova kellene a <%AppName%> alkalmazást telepíteni?"

SelectDestination,Title
"Válassza ki a cél könyvtárat"

SelectProgramFolder,AllUsersCheckbutton
"Létrehozza a program mappát az összes felhasználónak?"

SelectProgramFolder,BackButton
"< <%Back%>"

SelectProgramFolder,CancelButton
"<%Cancel%>"

SelectProgramFolder,Caption
"A telepít\u0151 a program ikonokat a lentebb listázott Program mappához fogja hozzáadni.  Megváltoztathatja az új mappa nevét, vagy kiválaszthat egy már létez\u0151t a listáról.  Kattintson a <%Next%> gombra a folytatáshoz."

SelectProgramFolder,FolderListLabel
"Létez\u0151 mappák:"

SelectProgramFolder,Message
""

SelectProgramFolder,NextButton
"<%Next%> >"

SelectProgramFolder,ProgramFolderLabel
"Program mappa:"

SelectProgramFolder,Subtitle
"Kérem válassza ki a program mappát!"

SelectProgramFolder,Title
"Program mappa kiválasztás"

SetupComplete,BackButton
"< <%Back%>"

SetupComplete,CancelButton
"<%Cancel%>"

SetupComplete,Caption
"InstallJammer Varázsló befejez\u0151dött"

SetupComplete,Message
"Az InstallJammer Varázsló sikeresen telepítette a <%AppName%> alkalmazást.  Kattintson a <%Finish%> gombra ahhoz, hogy kilépjen a varázslóból."

SetupComplete,NextButton
"<%Finish%>"

SetupType,BackButton
"< <%Back%>"

SetupType,CancelButton
"<%Cancel%>"

SetupType,Caption
"Válassza ki a kívánt telepítési típust!"

SetupType,DescriptionLabel
"Leírás"

SetupType,Message
""

SetupType,NextButton
"<%Next%> >"

SetupType,Subtitle
"Válassza ki az Önnek legjobban megfelel\u0151 telepítési módot."

SetupType,Title
"Telepítés típusa"

StartCopyingFiles,BackButton
"< <%Back%>"

StartCopyingFiles,CancelButton
"<%Cancel%>"

StartCopyingFiles,Caption
"A telepít\u0151nek elég információja van ahhoz, hogy a program állományait elkezdje másolni.  Ha meg akarja nézni vagy változtatni a beállításokat, akkor kattintson a <%Back%> gombra.  Ha elégedett a beállításokkal, akkor kattintson a <%Next%> gombra, hogy elkezd\u0151djön a fájlok másolása."

StartCopyingFiles,Message
""

StartCopyingFiles,NextButton
"<%Next%> >"

StartCopyingFiles,Subtitle
"Tekintse át a beállításokat, miel\u0151tt átmásolnánk az állományokat!"

StartCopyingFiles,Text
"Telepítési könyvtár:
 <%InstallDir%>

 Telepítés típusa:
 <%InstallType%>"

StartCopyingFiles,Title
"Állományok másolásának elkezdése"

Uninstall,BackButton
"< <%Back%>"

Uninstall,CancelButton
"<%Cancel%>"

Uninstall,Caption
"<%GroupBeingUninstalledText%>"

Uninstall,FileValue
"<%Status%>"

Uninstall,Message
""

Uninstall,NextButton
"<%Next%> >"

Uninstall,ProgressValue
"<%UninstallPercentComplete%>"

Uninstall,Subtitle
"A <%AppName%> alkalmazás eltávolítása"

Uninstall,Title
"Eltávolítás"

UninstallComplete,BackButton
"< <%Back%>"

UninstallComplete,CancelButton
"<%Cancel%>"

UninstallComplete,Caption
"Eltávolítás befejez\u0151dött"

UninstallComplete,Message
"A <%AppName%> alkalmazás el lett távolítva a rendszerér\u0151l."

UninstallComplete,NextButton
"<%Finish%>"

UninstallDetails,BackButton
"< <%Back%>"

UninstallDetails,CancelButton
"<%Cancel%>"

UninstallDetails,Caption
"A következ\u0151 hibák léptek fel az eltávolítás alatt:"

UninstallDetails,Message
""

UninstallDetails,NextButton
"<%Next%> >"

UninstallDetails,Subtitle
"Az eltávolítás alatt hiba lépett fel!"

UninstallDetails,Text
"<%Errors%>"

UninstallDetails,Title
"Eltávolítás részletei"

UserInformation,BackButton
"< <%Back%>"

UserInformation,CancelButton
"<%Cancel%>"

UserInformation,Caption
"Kérem írja be a nevét és a munkahelyének nevét."

UserInformation,CompanyLabel
"Cég:"

UserInformation,Message
""

UserInformation,NextButton
"<%Next%> >"

UserInformation,Subtitle
"Kérem írja ide az információkat."

UserInformation,Title
"Vásárlói információk"

UserInformation,UserNameLabel
"Felhasználó neve:"

Welcome,BackButton
"< <%Back%>"

Welcome,CancelButton
"<%Cancel%>"

Welcome,Caption
"Isten hozta a <%AppName%> InstallJammer Varázslójában"

Welcome,Message
"Ez a <%AppName%> alkalmazás <%Version%> verzióját fogja telepíteni a számítógépére.

 Javasoljuk, hogy zárjon be minden alkalmazást, miel\u0151tt folytatná.

 Kattintson a <%Next%> gombra a folytatáshoz vagy a <%Cancel%> gombra kilépéshez."

Welcome,NextButton
"<%Next%> >"
