ChooseComponents,BackButton
"< <%Back%>"

ChooseComponents,CancelButton
"<%Cancel%>"

ChooseComponents,Caption
"Selezionare le parti che si desidera installare e deselezionare le parti che non si desidera installare."

ChooseComponents,DescriptionLabel
"Descrizione"

ChooseComponents,Message
"<%SpaceRequiredText%> di spazio richiesto"

ChooseComponents,NextButton
"<%Next%> >"

ChooseComponents,Subtitle
"Selezionare le parti che saranno installate dal programma."

ChooseComponents,Title
"Selezionare le parti"

CopyFiles,BackButton
"< <%Back%>"

CopyFiles,CancelButton
"<%Cancel%>"

CopyFiles,Caption
"Si prega di attendere mentre il programma installa <%AppName%> sul computer."

CopyFiles,FileLabel
"<%Status%>"

CopyFiles,Message
""

CopyFiles,NextButton
"<%Next%> >"

CopyFiles,ProgressValue
"<%InstallPercentComplete%>"

CopyFiles,Subtitle
"Installazione di <%AppName%>"

CopyFiles,Title
"Installazione in corso"

CustomBlankPane1,BackButton
"< <%Back%>"

CustomBlankPane1,CancelButton
"<%Cancel%>"

CustomBlankPane1,Caption
"La didascalia va qui."

CustomBlankPane1,Message
"Il messaggio va qui."

CustomBlankPane1,NextButton
"<%Next%> >"

CustomBlankPane2,BackButton
"< <%Back%>"

CustomBlankPane2,CancelButton
"<%Cancel%>"

CustomBlankPane2,Caption
"Didascalia"

CustomBlankPane2,Message
"Messaggio"

CustomBlankPane2,NextButton
"<%Next%> >"

CustomBlankPane2,Subtitle
"Sottotitolo"

CustomBlankPane2,Title
"Titolo"

CustomTextPane1,BackButton
"< <%Back%>"

CustomTextPane1,CancelButton
"<%Cancel%>"

CustomTextPane1,Caption
"Didascalia"

CustomTextPane1,Message
"Messaggio"

CustomTextPane1,NextButton
"<%Next%> >"

CustomTextPane1,Subtitle
"Sottotitolo"

CustomTextPane1,Text
"Inserire qui il testo personalizzato."

CustomTextPane1,Title
"Titolo"

InstallPassword,BackButton
"< <%Back%>"

InstallPassword,CancelButton
"<%Cancel%>"

InstallPassword,Caption
"Si prega di inserire la parola chiave."

InstallPassword,Message
""

InstallPassword,NextButton
"<%Next%> >"

InstallPassword,Subtitle
"L'installazione richiede una parola chiave per proseguire."

InstallPassword,Title
"Parola chiave di installazione"

License,AcceptRadiobutton
"Accetto le condizioni del Contratto di licenza."

License,BackButton
"< <%Back%>"

License,CancelButton
"<%No%>"

License,DeclineRadiobutton
"Non accetto le condizioni del Contratto di licenza."

License,NextButton
"<%Yes%>"

License,Subtitle
"Si prega di leggere attentamente il contratto di licenza che segue."

License,Title
"Contratto di Licenza"

Readme,BackButton
"< <%Back%>"

Readme,CancelButton
"<%Cancel%>"

Readme,Caption
""

Readme,Message
""

Readme,NextButton
"<%Next%> >"

Readme,Subtitle
"Informazioni da leggere riguardo a <%AppName%>"

Readme,Text
""

Readme,Title
"Informazioni da leggere"

SelectDestination,BackButton
"< <%Back%>"

SelectDestination,BrowseButton
"<%Browse%>"

SelectDestination,BrowseText
"Per proseguire, premere su Avanti.  Se si desidera selezionare una cartella diversa, premere su Sfoglia."

SelectDestination,CancelButton
"<%Cancel%>"

SelectDestination,Caption
"Il programma di installazione installerà <%AppName%> nella seguente cartella.

Per installare in questa cartella, premere su Avanti.  Per installare in una cartella diversa, premere su Sfoglia e selezionare un'altra cartella."

SelectDestination,DestinationLabel
"Cartella di destinazione"

SelectDestination,Message
""

SelectDestination,NextButton
"<%Next%> >"

SelectDestination,Subtitle
"Dove si desidera installare <%AppName%>?"

SelectDestination,Title
"Scegliere la directory di destinazione"

SelectProgramFolder,AllUsersCheckbutton
"Crea la cartella del programma per tutti gli utenti"

SelectProgramFolder,BackButton
"< <%Back%>"

SelectProgramFolder,CancelButton
"<%Cancel%>"

SelectProgramFolder,Caption
"Il programma di installazione aggiungerà le icone del programma nella cartella elencata sotto.  Si può inserire il nome di una nuova cartella o selezionarla dalla lista delle cartelle esistenti.  Premere su Avanti per proseguire."

SelectProgramFolder,FolderListLabel
"Cartelle esistenti:"

SelectProgramFolder,Message
""

SelectProgramFolder,NextButton
"<%Next%> >"

SelectProgramFolder,ProgramFolderLabel
"Cartella del programma:"

SelectProgramFolder,Subtitle
"Si prega di selezionare la cartella del programma."

SelectProgramFolder,Title
"Selezionare la cartella del programma"

SetupComplete,BackButton
"< <%Back%>"

SetupComplete,CancelButton
"<%Cancel%>"

SetupComplete,Caption
"Autocomposizione di InstallJammer completata"

SetupComplete,Message
"L'autocomposizione di InstallJammer ha installato <%AppName%> con successo.  Premere su Fine per uscire dall'autocomposizione."

SetupComplete,NextButton
"<%Finish%>"

SetupType,BackButton
"< <%Back%>"

SetupType,CancelButton
"<%Cancel%>"

SetupType,Caption
"Scegliere la tipologia di installazione che si preferisce."

SetupType,DescriptionLabel
"Descrizione"

SetupType,Message
""

SetupType,NextButton
"<%Next%> >"

SetupType,Subtitle
"Selezionare la tipologia di installazione più adatta alle proprie esigenze."

SetupType,Title
"Tipologia di installazione"

StartCopyingFiles,BackButton
"< <%Back%>"

StartCopyingFiles,CancelButton
"<%Cancel%>"

StartCopyingFiles,Caption
"Il programma di installazione ha sufficienti informazioni per iniziare la copia dei file del programma.  Se si desidera controllare o modificare le impostazioni, premere Indietro.  Se si è soddisfatti delle impostazioni, premere Avanti per iniziare a copiare i file."

StartCopyingFiles,Message
""

StartCopyingFiles,NextButton
"<%Next%> >"

StartCopyingFiles,Subtitle
"Controllo delle impostazioni prima della copia dei file"

StartCopyingFiles,Text
"Directory di installazione:
 <%InstallDir%>

 Tipologia di installazione:
 <%InstallType%>"

StartCopyingFiles,Title
"Inizio della copia dei file"

Uninstall,BackButton
"< <%Back%>"

Uninstall,CancelButton
"<%Cancel%>"

Uninstall,Caption
"<%GroupBeingUninstalledText%>"

Uninstall,FileValue
"<%Status%>"

Uninstall,Message
""

Uninstall,NextButton
"<%Next%> >"

Uninstall,ProgressValue
"<%UninstallPercentComplete%>"

Uninstall,Subtitle
"Disinstallazione di <%AppName%>"

Uninstall,Title
"Disinstallazione in corso"

UninstallComplete,BackButton
"< <%Back%>"

UninstallComplete,CancelButton
"<%Cancel%>"

UninstallComplete,Caption
"Disinstallazione completata"

UninstallComplete,Message
"<%AppName%> è stato rimosso dal sistema."

UninstallComplete,NextButton
"<%Finish%>"

UninstallDetails,BackButton
"< <%Back%>"

UninstallDetails,CancelButton
"<%Cancel%>"

UninstallDetails,Caption
"I seguenti errori sono occorsi durante la rimozione:"

UninstallDetails,Message
""

UninstallDetails,NextButton
"<%Next%> >"

UninstallDetails,Subtitle
"Durante la rimozione sono occorsi degli errori"

UninstallDetails,Text
"<%Errors%>"

UninstallDetails,Title
"Dettagli della disinstallazione"

UserInformation,BackButton
"< <%Back%>"

UserInformation,CancelButton
"<%Cancel%>"

UserInformation,Caption
"Si prega di inserire il proprio nome e il nome della società per cui si lavora."

UserInformation,CompanyLabel
"Società:"

UserInformation,Message
""

UserInformation,NextButton
"<%Next%> >"

UserInformation,Subtitle
"Si prega di inserire le informazioni."

UserInformation,Title
"Informazioni sul cliente"

UserInformation,UserNameLabel
"Nome dell'utente:"

Welcome,BackButton
"< <%Back%>"

Welcome,CancelButton
"<%Cancel%>"

Welcome,Caption
"Benvenuti nell'autocomposizione di InstallJammer per <%AppName%>"

Welcome,Message
"Si sta per installare <%AppName%> nella versione <%Version%> sul computer.  

E' consigliata la chiusura di tutte le altre applicazioni prima di proseguire.

Premere su Avanti per continuare o su Annulla per uscire dall'installazione."

Welcome,NextButton
"<%Next%> >"
