ChooseComponents,BackButton
"< <%Back%>"

ChooseComponents,CancelButton
"<%Cancel%>"

ChooseComponents,Caption
"Selecteer de componenten die u wilt installeren en deselecteer de componenten die u niet wilt installeren."

ChooseComponents,DescriptionLabel
"Omschrijving"

ChooseComponents,Message
"<%SpaceRequiredText%> aan ruimte benodigd"

ChooseComponents,NextButton
"<%Next%> >"

ChooseComponents,Subtitle
"Selecteer de componenten die het installatie programma zal installeren."

ChooseComponents,Title
"Selecteer Componenten"

CopyFiles,BackButton
"< <%Back%>"

CopyFiles,CancelButton
"<%Cancel%>"

CopyFiles,Caption
"Een ogenblik geduld terwijl <%AppName%> wordt geïnstalleerd op uw computer."

CopyFiles,FileLabel
"<%Status%>"

CopyFiles,Message
""

CopyFiles,NextButton
"<%Next%> >"

CopyFiles,ProgressValue
"<%InstallPercentComplete%>"

CopyFiles,Subtitle
"<%AppName%> installeren"

CopyFiles,Title
"Installeren"

CustomBlankPane1,BackButton
"< <%Back%>"

CustomBlankPane1,CancelButton
"<%Cancel%>"

CustomBlankPane1,Caption
"Bijschrift hier."

CustomBlankPane1,Message
"Bericht hier."

CustomBlankPane1,NextButton
"<%Next%> >"

CustomBlankPane2,BackButton
"< <%Back%>"

CustomBlankPane2,CancelButton
"<%Cancel%>"

CustomBlankPane2,Caption
"Bijschrift"

CustomBlankPane2,Message
"Bericht"

CustomBlankPane2,NextButton
"<%Next%> >"

CustomBlankPane2,Subtitle
"Ondertitel"

CustomBlankPane2,Title
"Titel"

CustomTextPane1,BackButton
"< <%Back%>"

CustomTextPane1,CancelButton
"<%Cancel%>"

CustomTextPane1,Caption
"Bijschrift"

CustomTextPane1,Message
"Bericht"

CustomTextPane1,NextButton
"<%Next%> >"

CustomTextPane1,Subtitle
"Ondertitel"

CustomTextPane1,Text
"Zet uw eigen tekst hier."

CustomTextPane1,Title
"Titel"

InstallPassword,BackButton
"< <%Back%>"

InstallPassword,CancelButton
"<%Cancel%>"

InstallPassword,Caption
"Vul uw wachtwoord in."

InstallPassword,Message
""

InstallPassword,NextButton
"<%Next%> >"

InstallPassword,Subtitle
"Deze installatie vereist een wachtwoord om door te kunnen gaan."

InstallPassword,Title
"Installatie Wachtwoord"

License,AcceptRadiobutton
"Ik ga akkoord met de licentie overeenkomst."

License,BackButton
"< <%Back%>"

License,CancelButton
"Stop Installatie"

License,DeclineRadiobutton
"Ik ga NIET akkoord met de licentie overeenkomst."

License,NextButton
"<%Yes%>"

License,Subtitle
"Lees de licentie overeenkomst aandachtig."

License,Title
"Licentie Overeenkomst"

Readme,BackButton
"< <%Back%>"

Readme,CancelButton
"<%Cancel%>"

Readme,Caption
""

Readme,Message
""

Readme,NextButton
"<%Next%> >"

Readme,Subtitle
"Readme Informatie voor <%AppName%>"

Readme,Text
""

Readme,Title
"Readme Informatie"

SelectDestination,BackButton
"< <%Back%>"

SelectDestination,BrowseButton
"<%Browse%>"

SelectDestination,BrowseText
"Als u de installatie locatie wilt wijzigen klikt u op 'Selecteer map' en selecteert u een nieuwe locatie.
 Om verder te gaan met het installatieproces klikt u op Volgende."

SelectDestination,CancelButton
"<%Cancel%>"

SelectDestination,Caption
"Dit installatie programma zal <%AppName%> in de onderstaande map installeren."

SelectDestination,DestinationLabel
"Installatie map"

SelectDestination,Message
""

SelectDestination,NextButton
"<%Next%> >"

SelectDestination,Subtitle
"Waar moet <%AppName%> worden geïnstalleerd?"

SelectDestination,Title
"Kies de installatie map"

SelectProgramFolder,AllUsersCheckbutton
"Maak programma map voor alle gebruikers"

SelectProgramFolder,BackButton
"< <%Back%>"

SelectProgramFolder,CancelButton
"<%Cancel%>"

SelectProgramFolder,Caption
"Het installatie programma zal de programma iconen toevoegen aan de onderstaande Programma map.  U kunt een nieuwe map aanmaken of een bestaande map selecteren uit de lijst.  Klik op Volgende om door te gaan."

SelectProgramFolder,FolderListLabel
"Huidige mappen:"

SelectProgramFolder,Message
""

SelectProgramFolder,NextButton
"<%Next%> >"

SelectProgramFolder,ProgramFolderLabel
"Programma map:"

SelectProgramFolder,Subtitle
"U kunt de Programma map selecteren."

SelectProgramFolder,Title
"Selecteer Programma Map"

SetupComplete,BackButton
"< <%Back%>"

SetupComplete,CancelButton
"<%Cancel%>"

SetupComplete,Caption
"Installatie Programma Afgerond"

SetupComplete,Message
"Het installatie programma heeft <%AppName%> succesvol geïnstalleerd.  Klik op <%Finish%> om het installatie programma te sluiten."

SetupComplete,NextButton
"<%Finish%>"

SetupType,BackButton
"< <%Back%>"

SetupType,CancelButton
"<%Cancel%>"

SetupType,Caption
"Kies het type setup dat u prefereerd."

SetupType,DescriptionLabel
"Omschrijving"

SetupType,Message
""

SetupType,NextButton
"<%Next%> >"

SetupType,Subtitle
"Kies het type setup dat u prefereerd."

SetupType,Title
"Setup Type"

StartCopyingFiles,BackButton
"< <%Back%>"

StartCopyingFiles,CancelButton
"<%Cancel%>"

StartCopyingFiles,Caption
"Het installatie programma heeft genoeg informatie om het kopiëren te starten.  Als u de instellingen wilt bekijken of wijzigen kunt op <%Back%> klikken.  Als u tevreden bent met de instellingen klikt u op <%Next%> om het kopiëren te starten."

StartCopyingFiles,Message
""

StartCopyingFiles,NextButton
"<%Next%> >"

StartCopyingFiles,Subtitle
"Bekijk uw instellingen voordat het installeren begint"

StartCopyingFiles,Text
"Installatie directory:
 <%InstallDir%>

 Setup type:
 <%InstallType%>"

StartCopyingFiles,Title
"Start Kopiëren Bestanden"

Uninstall,BackButton
"< <%Back%>"

Uninstall,CancelButton
"<%Cancel%>"

Uninstall,Caption
"<%GroupBeingUninstalledText%>"

Uninstall,FileValue
"<%Status%>"

Uninstall,Message
""

Uninstall,NextButton
"<%Next%> >"

Uninstall,ProgressValue
"<%UninstallPercentComplete%>"

Uninstall,Subtitle
"<%AppName%> deïnstalleren"

Uninstall,Title
"Deïnstalleren"

UninstallComplete,BackButton
"< <%Back%>"

UninstallComplete,CancelButton
"<%Cancel%>"

UninstallComplete,Caption
"Deïnstallatie afgerond"

UninstallComplete,Message
"<%AppName%> is van uw systeem verwijderd."

UninstallComplete,NextButton
"<%Finish%>"

UninstallDetails,BackButton
"< <%Back%>"

UninstallDetails,CancelButton
"<%Cancel%>"

UninstallDetails,Caption
"De volgende fouten hebben zicht voorgedaan tijdens de deïnstallatie:"

UninstallDetails,Message
""

UninstallDetails,NextButton
"<%Next%> >"

UninstallDetails,Subtitle
"Er hebben zich fouten voorgedaan tijdens de deïnstallatie"

UninstallDetails,Text
"<%Errors%>"

UninstallDetails,Title
"Deïnstallatie Details"

UserInformation,BackButton
"< <%Back%>"

UserInformation,CancelButton
"<%Cancel%>"

UserInformation,Caption
"Vul uw naam en uw bedrijfsnaam in."

UserInformation,CompanyLabel
"Bedrijfsnaam:"

UserInformation,Message
""

UserInformation,NextButton
"<%Next%> >"

UserInformation,Subtitle
"Vul uw informatie in."

UserInformation,Title
"Gebruikers Informatie"

UserInformation,UserNameLabel
"Naam:"

Welcome,BackButton
"< <%Back%>"

Welcome,CancelButton
"<%Cancel%>"

Welcome,Caption
"Welkom bij het <%AppName%> installatie programma.  Dit programma zal <%AppName%> op uw computer installeren."

Welcome,Message
"Het is aan te raden alle overige applicaties te sluiten alvorens verder te gaan met deze installatie.

Klik op <%Next%> om verder te gaan of op <%Cancel%> om deze installatie af te breken"

Welcome,NextButton
"<%Next%> >"
