ChooseComponents,BackButton
"< <%Back%>"

ChooseComponents,CancelButton
"<%Cancel%>"

ChooseComponents,Caption
"Zaznacz komponenty, które chcesz zainstalować, a odznacz te, których nie chcesz instalować."

ChooseComponents,DescriptionLabel
"Opis"

ChooseComponents,Message
"Wymagane miejsce na dysku: <%SpaceRequiredText%>"

ChooseComponents,NextButton
"<%Next%> >"

ChooseComponents,Subtitle
"Wybierz komponenty do zainstalowania."

ChooseComponents,Title
"Wybierz komponenty"

CopyFiles,BackButton
"< <%Back%>"

CopyFiles,CancelButton
"<%Cancel%>"

CopyFiles,Caption
"Proszę czekać podczas, gdy Instalator instaluje <%AppName%> na twoim komputerze."

CopyFiles,FileLabel
"<%Status%>"

CopyFiles,Message
""

CopyFiles,NextButton
"<%Next%> >"

CopyFiles,ProgressValue
"<%InstallPercentComplete%>"

CopyFiles,Subtitle
"Instalowanie <%AppName%>"

CopyFiles,Title
"Instalowanie"

CustomBlankPane1,BackButton
"< <%Back%>"

CustomBlankPane1,CancelButton
"<%Cancel%>"

CustomBlankPane1,Caption
"Caption goes here."

CustomBlankPane1,Message
"Message goes here."

CustomBlankPane1,NextButton
"<%Next%> >"

CustomBlankPane2,BackButton
"< <%Back%>"

CustomBlankPane2,CancelButton
"<%Cancel%>"

CustomBlankPane2,Caption
"Nagłówek"

CustomBlankPane2,Message
"Wiadomość"

CustomBlankPane2,NextButton
"<%Next%> >"

CustomBlankPane2,Subtitle
"Podtytuł"

CustomBlankPane2,Title
"Tytuł"

CustomTextPane1,BackButton
"< <%Back%>"

CustomTextPane1,CancelButton
"<%Cancel%>"

CustomTextPane1,Caption
"Nagłówek"

CustomTextPane1,Message
"Wiadomość"

CustomTextPane1,NextButton
"<%Next%> >"

CustomTextPane1,Subtitle
"podtytuł"

CustomTextPane1,Text
"Tutaj wpisuj swój tekst."

CustomTextPane1,Title
"Tytuł"

License,AcceptRadiobutton
"Akceptuję warunki licencji."

License,BackButton
"< <%Back%>"

License,CancelButton
"<%No%>"

License,DeclineRadiobutton
"Nie akceptuję warunków licencji."

License,NextButton
"<%Yes%>"

License,Subtitle
"Proszę uważnie przeczytać poniższą licencję."

License,Title
"Warunki licencji"

Readme,BackButton
"< <%Back%>"

Readme,CancelButton
"<%Cancel%>"

Readme,Caption
""

Readme,Message
""

Readme,NextButton
"<%Next%> >"

Readme,Subtitle
"Informacje Readme dla <%AppName%>"

Readme,Text
""

Readme,Title
"Informacje Readme"

SelectDestination,BackButton
"< <%Back%>"

SelectDestination,BrowseButton
"<%Browse%>"

SelectDestination,BrowseText
"Aby kontynuować, kliknij Dalej.  Jeśli chcesz wybrać inny folder, kliknij Przeglądaj."

SelectDestination,CancelButton
"<%Cancel%>"

SelectDestination,Caption
"Instalator zainstaluje <%AppName%> w wybranym folderze.

Aby instalować w tym folderze, kliknij Dalej.  Aby zainstalować w innym folderze, kliknij Przeglądaj i wybierz inny folder."

SelectDestination,DestinationLabel
"Folder docelowy"

SelectDestination,Message
""

SelectDestination,NextButton
"<%Next%> >"

SelectDestination,Subtitle
"Gdzie zainstalować <%AppName%>?"

SelectDestination,Title
"Wybierz folder docelowy"

SelectProgramFolder,AllUsersCheckbutton
"Utwórz folder programu dla wszystkich użytkowników"

SelectProgramFolder,BackButton
"< <%Back%>"

SelectProgramFolder,CancelButton
"<%Cancel%>"

SelectProgramFolder,Caption
"Instalator doda ikonki programu w folderze aplikacji wybranym poniżej.  Możesz wprowadzić nową nazwę folderu lub wybrać z listy już istniejących.  Kliknij Dalej, aby kontynuować."

SelectProgramFolder,FolderListLabel
"Istniejące foldery:"

SelectProgramFolder,Message
""

SelectProgramFolder,NextButton
"<%Next%> >"

SelectProgramFolder,ProgramFolderLabel
"Folder programu:"

SelectProgramFolder,Subtitle
"Przoszę wybrać folder dla programu."

SelectProgramFolder,Title
"Wybierz folder programu"

SetupComplete,BackButton
"< <%Back%>"

SetupComplete,CancelButton
"<%Cancel%>"

SetupComplete,Caption
"InstallJammer - Instalacja zakończona"

SetupComplete,Message
"Instalator InstallJammer zainstalował pomyślnie <%AppName%>.  Kliknij Zakończ, aby opuścić instalator."

SetupComplete,NextButton
"<%Finish%>"

SetupType,BackButton
"< <%Back%>"

SetupType,CancelButton
"<%Cancel%>"

SetupType,Caption
"Kliknij preferowany typ instalacji."

SetupType,DescriptionLabel
"Opis"

SetupType,Message
""

SetupType,NextButton
"<%Next%> >"

SetupType,Subtitle
"Wybierz typ instalacji, który Ci odpowiada."

SetupType,Title
"Typ instalacji"

StartCopyingFiles,BackButton
"< <%Back%>"

StartCopyingFiles,CancelButton
"<%Cancel%>"

StartCopyingFiles,Caption
"Instalator posiada już wszystkie informacje potrzebnedo rozpoczęcia kopiowania plików.  Jeśli chcesz zobaczyć ustawienia lub zmienić je, kliknij Wstecz.  Jeśli jesteś pewien ustawień, kliknij Dalej, aby rozpocząć kopiowanie plików."

StartCopyingFiles,Message
""

StartCopyingFiles,NextButton
"<%Next%> >"

StartCopyingFiles,Subtitle
"Pokaż ustawienia przed rozpoczęciem kopiowania plików"

StartCopyingFiles,Text
"Folder docelowy:
 <%InstallDir%>

 Typ instalacji:
 <%InstallType%>"

StartCopyingFiles,Title
"Rozpocznij kopiowanie plików"

Uninstall,BackButton
"< <%Back%>"

Uninstall,CancelButton
"<%Cancel%>"

Uninstall,Caption
"<%GroupBeingUninstalledText%>"

Uninstall,FileValue
"<%Status%>"

Uninstall,Message
""

Uninstall,NextButton
"<%Next%> >"

Uninstall,ProgressValue
"<%UninstallPercentComplete%>"

Uninstall,Subtitle
"Deinstalacja <%AppName%>"

Uninstall,Title
"Usuwanie"

UninstallComplete,BackButton
"< <%Back%>"

UninstallComplete,CancelButton
"<%Cancel%>"

UninstallComplete,Caption
"Usuwanie zakończone"

UninstallComplete,Message
"Usunięto pomyślnie <%AppName%> z twojego systemu."

UninstallComplete,NextButton
"<%Finish%>"

UninstallDetails,BackButton
"< <%Back%>"

UninstallDetails,CancelButton
"<%Cancel%>"

UninstallDetails,Caption
"Napotkano następujące błędy podczas usuwania:"

UninstallDetails,Message
""

UninstallDetails,NextButton
"<%Next%> >"

UninstallDetails,Subtitle
"Błędy podczas usuwania"

UninstallDetails,Text
"<%Errors%>"

UninstallDetails,Title
"Detale deinstalacji"

UserInformation,BackButton
"< <%Back%>"

UserInformation,CancelButton
"<%Cancel%>"

UserInformation,Caption
"Proszę podać nazwisko i nazwę firmy, dla której pracujesz."

UserInformation,CompanyLabel
"Firma:"

UserInformation,Message
""

UserInformation,NextButton
"<%Next%> >"

UserInformation,Subtitle
"Proszę wpisać swoje dane."

UserInformation,Title
"Informacje o kliencie"

UserInformation,UserNameLabel
"Nazwa użytkownika:"

Welcome,BackButton
"< <%Back%>"

Welcome,CancelButton
"<%Cancel%>"

Welcome,Caption
"Witamy w InstallJammer - instalatorze dla <%AppName%>"

Welcome,Message
"Zainstaluje on <%AppName%> w wersji <%Version%> na twoim komputerze.  

Zalecane jest zamknięcie wszystkich programów przed instalacją.  

Kliknij Dalej, aby kontynuować lub Anuluj, aby opuścić instalator."

Welcome,NextButton
"<%Next%> >"
