ChooseComponents,BackButton
"< <%Back%>"

ChooseComponents,CancelButton
"<%Cancel%>"

ChooseComponents,Caption
"Selecione os componentes que você quer instalar e deselecione os componentes que você não quer instalar."

ChooseComponents,DescriptionLabel
"Descrição"

ChooseComponents,Message
"<%SpaceRequiredText%> de espaço é necessário"

ChooseComponents,NextButton
"<%Next%> >"

ChooseComponents,Subtitle
"Selecione os componentes que seão instalados."

ChooseComponents,Title
"Selecionar Componentes"

CopyFiles,BackButton
"< <%Back%>"

CopyFiles,CancelButton
"<%Cancel%>"

CopyFiles,Caption
"Por favor, aguarde enquanto o programa <%AppName%> é instalado em seu computador."

CopyFiles,FileLabel
"<%Status%>"

CopyFiles,Message
""

CopyFiles,NextButton
"<%Next%> >"

CopyFiles,ProgressValue
"<%InstallPercentComplete%>"

CopyFiles,Subtitle
"Instalando <%AppName%>"

CopyFiles,Title
"Instalando"

CustomBlankPane1,BackButton
"< <%Back%>"

CustomBlankPane1,CancelButton
"<%Cancel%>"

CustomBlankPane1,Caption
"Caption irá aqui."

CustomBlankPane1,Message
"Mensagem irá aqui."

CustomBlankPane1,NextButton
"<%Next%> >"

CustomBlankPane2,BackButton
"< <%Back%>"

CustomBlankPane2,CancelButton
"<%Cancel%>"

CustomBlankPane2,Caption
"Caption"

CustomBlankPane2,Message
"Mensagem"

CustomBlankPane2,NextButton
"<%Next%> >"

CustomBlankPane2,Subtitle
"Subtítulo"

CustomBlankPane2,Title
"Título"

CustomTextPane1,BackButton
"< <%Back%>"

CustomTextPane1,CancelButton
"<%Cancel%>"

CustomTextPane1,Caption
"Caption"

CustomTextPane1,Message
"Mensagem"

CustomTextPane1,NextButton
"<%Next%> >"

CustomTextPane1,Subtitle
"Subtítulo"

CustomTextPane1,Text
"Coloque seu texto personalizado aqui."

CustomTextPane1,Title
"Título"

License,AcceptRadiobutton
"Eu concordo os termos da licença."

License,BackButton
"< <%Back%>"

License,CancelButton
"<%No%>"

License,DeclineRadiobutton
"Eu não concordo com os termos da licença."

License,NextButton
"<%Yes%>"

License,Subtitle
"Por favor, leia os termos da licença cuidadosamente."

License,Title
"Concordância com a Licença"

Readme,BackButton
"< <%Back%>"

Readme,CancelButton
"<%Cancel%>"

Readme,Caption
""

Readme,Message
""

Readme,NextButton
"<%Next%> >"

Readme,Subtitle
"Informações do Readme para <%AppName%>"

Readme,Text
""

Readme,Title
"Informações do Readme"

SelectDestination,BackButton
"< <%Back%>"

SelectDestination,BrowseButton
"<%Browse%>"

SelectDestination,BrowseText
"Para continuar, clique em Próximo.  Se você deseja selecionar uma pasta diferente, clique em Procurar."

SelectDestination,CancelButton
"<%Cancel%>"

SelectDestination,Caption
"A Instalação irá instalar <%AppName%> na seguinte pasta.

Para instalar nesta pasta, clique em Próximo.  Para instalar em uma pasta diferente, clique em Procurar e selecione outra pasta."

SelectDestination,DestinationLabel
"Pasta de Destino"

SelectDestination,Message
""

SelectDestination,NextButton
"<%Next%> >"

SelectDestination,Subtitle
"Onde o <%AppName%> deverá ser instalado?"

SelectDestination,Title
"Escolha a localização de destino"

SelectProgramFolder,AllUsersCheckbutton
"Criar uma pasta de programa para todos os usuários"

SelectProgramFolder,BackButton
"< <%Back%>"

SelectProgramFolder,CancelButton
"<%Cancel%>"

SelectProgramFolder,Caption
"A Instalação adicionará os ícones do programa Pasta de Programas listada abaixo.  Você poderá digitar um novo nome de pasta or selecionar uma das pastas da lista.  Clique em Próximo para continuar."

SelectProgramFolder,FolderListLabel
"Pastas Existentes:"

SelectProgramFolder,Message
""

SelectProgramFolder,NextButton
"<%Next%> >"

SelectProgramFolder,ProgramFolderLabel
"Pasta de Programas:"

SelectProgramFolder,Subtitle
"Por favor, selecione uma pasta de programa."

SelectProgramFolder,Title
"Selecione a Pasta de Programas"

SetupComplete,BackButton
"< <%Back%>"

SetupComplete,CancelButton
"<%Cancel%>"

SetupComplete,Caption
"Assistente InstallJammer Concluído"

SetupComplete,Message
"O Assistente InstallJammer instalou com sucesso o <%AppName%>.  Clique em Concluir para sair do assistente."

SetupComplete,NextButton
"<%Finish%>"

SetupType,BackButton
"< <%Back%>"

SetupType,CancelButton
"<%Cancel%>"

SetupType,Caption
"Clique no tipo de Instalação de sua preferência."

SetupType,DescriptionLabel
"Descrição"

SetupType,Message
""

SetupType,NextButton
"<%Next%> >"

SetupType,Subtitle
"Seleciona o tipo de instalação que melhor de adapta às suas necessidades."

SetupType,Title
"Tipo de Instalação"

StartCopyingFiles,BackButton
"< <%Back%>"

StartCopyingFiles,CancelButton
"<%Cancel%>"

StartCopyingFiles,Caption
"A Instalação tem bastante informação para iniciar a cópia dos arquivos do programa.  Se você deseja revisar or mudar qualquer configuração, clique em Voltar.  Se você está satisfeito com as configurações, clique em Próximo para iniciar a cópia dos arquivos."

StartCopyingFiles,Message
""

StartCopyingFiles,NextButton
"<%Next%> >"

StartCopyingFiles,Subtitle
"Reveja as configurações antes de copiar os arquivos"

StartCopyingFiles,Text
"Diretório de Instalação:
	<%InstallDir%>

Tipo de Instalação:
	<%InstallType%>"

StartCopyingFiles,Title
"Iniciar Cópia de Arquivos"

Uninstall,BackButton
"< <%Back%>"

Uninstall,CancelButton
"<%Cancel%>"

Uninstall,Caption
"<%GroupBeingUninstalledText%>"

Uninstall,FileValue
"<%Status%>"

Uninstall,Message
""

Uninstall,NextButton
"<%Next%> >"

Uninstall,ProgressValue
"<%UninstallPercentComplete%>"

Uninstall,Subtitle
"Desinstalando <%AppName%>"

Uninstall,Title
"Desinstalando"

UninstallComplete,BackButton
"< <%Back%>"

UninstallComplete,CancelButton
"<%Cancel%>"

UninstallComplete,Caption
"Desinstalação Concluída"

UninstallComplete,Message
"<%AppName%> foi removido do seu sistema."

UninstallComplete,NextButton
"<%Finish%>"

UninstallDetails,BackButton
"< <%Back%>"

UninstallDetails,CancelButton
"<%Cancel%>"

UninstallDetails,Caption
"Os seguintes error ocorreram durante a desinstalação:"

UninstallDetails,Message
""

UninstallDetails,NextButton
"<%Next%> >"

UninstallDetails,Subtitle
"Erros ocurreram durante a desinstalação"

UninstallDetails,Text
"<%Errors%>"

UninstallDetails,Title
"Detalhes de Desinstalação"

UserInformation,BackButton
"< <%Back%>"

UserInformation,CancelButton
"<%Cancel%>"

UserInformation,Caption
"Por favor, digite seu nome e o nome da empresa onde você trabalha."

UserInformation,CompanyLabel
"Empresa:"

UserInformation,Message
""

UserInformation,NextButton
"<%Next%> >"

UserInformation,Subtitle
"Por favor, digite as tuas informações."

UserInformation,Title
"Informações do Proprietário"

UserInformation,UserNameLabel
"Nome do Usuário:"

Welcome,BackButton
"< <%Back%>"

Welcome,CancelButton
"<%Cancel%>"

Welcome,Caption
"Bem vindo ao Assistente InstallJammer para o <%AppName%>"

Welcome,Message
"Será instalado <%AppName%> version <%Version%> em seu computador.

É recomendado que você feche todos os outros programas antes de continuar.  

Clique em Próximo para continuar ou em Cancelar para sair da Instalação."

Welcome,NextButton
"<%Next%> >"
