ChooseComponents,BackButton
"< <%Back%>"

ChooseComponents,CancelButton
"<%Cancel%>"

ChooseComponents,Caption
"Отметьте компоненты, которые вы хотите установить, и снимите отметку с тех компонент, которые вы не желаете устанавливать."

ChooseComponents,DescriptionLabel
"Описание"

ChooseComponents,Message
"Для установки требуется <%SpaceRequiredText%> на жестком диске"

ChooseComponents,NextButton
"<%Next%> >"

ChooseComponents,Subtitle
"Выберите компоненты, которые вы хотите установить."

ChooseComponents,Title
"Выбор компонент для установки"

CopyFiles,BackButton
"< <%Back%>"

CopyFiles,CancelButton
"<%Cancel%>"

CopyFiles,Caption
"Идёт установка <%AppName%> на Ваш компьютер.  Пожалуйста, подождите."

CopyFiles,FileLabel
"<%Status%>"

CopyFiles,Message
""

CopyFiles,NextButton
"<%Next%> >"

CopyFiles,ProgressValue
"<%InstallPercentComplete%>"

CopyFiles,Subtitle
"Установка <%AppName%>"

CopyFiles,Title
"Установка"

CustomBlankPane1,BackButton
"< <%Back%>"

CustomBlankPane1,CancelButton
"<%Cancel%>"

CustomBlankPane1,Caption
"Здесь должна быть подпись."

CustomBlankPane1,Message
"Здесь должно быть сообщение."

CustomBlankPane1,NextButton
"<%Next%> >"

CustomBlankPane2,BackButton
"< <%Back%>"

CustomBlankPane2,CancelButton
"<%Cancel%>"

CustomBlankPane2,Caption
"Подпись"

CustomBlankPane2,Message
"Сообщение"

CustomBlankPane2,NextButton
"<%Next%> >"

CustomBlankPane2,Subtitle
"Подзаголовок"

CustomBlankPane2,Title
"Заголовок"

CustomTextPane1,BackButton
"< <%Back%>"

CustomTextPane1,CancelButton
"<%Cancel%>"

CustomTextPane1,Caption
"Подпись"

CustomTextPane1,Message
"Сообщение"

CustomTextPane1,NextButton
"<%Next%> >"

CustomTextPane1,Subtitle
"Подзаголовок"

CustomTextPane1,Text
"Здесь впишите текст."

CustomTextPane1,Title
"Заголовок"

InstallPassword,BackButton
"< <%Back%>"

InstallPassword,CancelButton
"<%Cancel%>"

InstallPassword,Caption
"Пожалуйста, введите пароль."

InstallPassword,Message
""

InstallPassword,NextButton
"<%Next%> >"

InstallPassword,Subtitle
"Для продолжения установки необходимо указать пароль."

InstallPassword,Title
"Пароль установки"

License,AcceptRadiobutton
"Я принимаю положения лицензионного соглашения."

License,BackButton
"< <%Back%>"

License,CancelButton
"<%No%>"

License,DeclineRadiobutton
"Я не принимаю положения лицензионного соглашения."

License,NextButton
"<%Yes%>"

License,Subtitle
"Пожалуйста, внимательно прочтите приведённое ниже лицензионное соглашение."

License,Text
"Здесь должно быть лицензионное соглашение."

License,Title
"Лицензионное Соглашение"

Readme,BackButton
"< <%Back%>"

Readme,CancelButton
"<%Cancel%>"

Readme,Caption
""

Readme,Message
""

Readme,NextButton
"<%Next%> >"

Readme,Subtitle
"Информация о <%AppName%>"

Readme,Text
""

Readme,Title
"Информация"

SelectDestination,BackButton
"< <%Back%>"

SelectDestination,BrowseButton
"<%Browse%>"

SelectDestination,BrowseText
"Для продолжения щёлкните по <%Next%>.  Для указания другого каталога щёлкните по <%Browse%>."

SelectDestination,CancelButton
"<%Cancel%>"

SelectDestination,Caption
"<%AppName%> будет установлена в указанный ниже каталог.

Чтобы произвести установку в этот каталог, щёлкните по <%Next%>.  Чтобы произвести установку в другой каталог, щёлкните по <%Browse%>."

SelectDestination,DestinationLabel
"Каталог назначения"

SelectDestination,Message
""

SelectDestination,NextButton
"<%Next%> >"

SelectDestination,Subtitle
"Где нужно установить <%AppName%> ?"

SelectDestination,Title
"Укажите каталог назначения"

SelectProgramFolder,AllUsersCheckbutton
"Создать программную группу для всех пользователей"

SelectProgramFolder,BackButton
"< <%Back%>"

SelectProgramFolder,CancelButton
"<%Cancel%>"

SelectProgramFolder,Caption
"Ярлыки программы будут добавлены в указанную ниже программную группу.  Вы можете указать другую группу, либо выбрать группу из списка существующих.  Для продолжения щёлкните по <%Next%>."

SelectProgramFolder,FolderListLabel
"Существующие программные группы:"

SelectProgramFolder,Message
""

SelectProgramFolder,NextButton
"<%Next%> >"

SelectProgramFolder,ProgramFolderLabel
"Программная группа:"

SelectProgramFolder,Subtitle
"Пожалуйста, выберите программную группу."

SelectProgramFolder,Title
"Укажите программную группу"

SetupComplete,BackButton
"< <%Back%>"

SetupComplete,CancelButton
"<%Cancel%>"

SetupComplete,Caption
"Установка завершена"

SetupComplete,Message
"Мастер InstallJammer успешно установил <%AppName%>.  Выберите <%Finish%>, чтобы закрыть мастер."

SetupComplete,NextButton
"<%Finish%>"

SetupType,BackButton
"< <%Back%>"

SetupType,CancelButton
"<%Cancel%>"

SetupType,Caption
"Щёлкните по нужному вам типу установки."

SetupType,DescriptionLabel
"Описание"

SetupType,Message
""

SetupType,NextButton
"<%Next%> >"

SetupType,Subtitle
"Выберите тип установки, который вам больше всего подходит."

SetupType,Title
"Тип установки"

StartCopyingFiles,BackButton
"< <%Back%>"

StartCopyingFiles,CancelButton
"<%Cancel%>"

StartCopyingFiles,Caption
"Программа установки собрала необходимую информацию для начала копирования файлов.  Щёлкните по <%Back%>, чтобы проверить или заново ввести информацию для установки.  Чтобы начать установку, щёлкните по <%Next%>."

StartCopyingFiles,Message
""

StartCopyingFiles,NextButton
"<%Next%> >"

StartCopyingFiles,Subtitle
"Просмотр информации перед началом копирования файлов"

StartCopyingFiles,Text
"Каталог назначения:
 <%InstallDir%>

 Тип установки:
 <%InstallType%>"

StartCopyingFiles,Title
"Начало копирования файлов"

Uninstall,BackButton
"< <%Back%>"

Uninstall,CancelButton
"<%Cancel%>"

Uninstall,Caption
"<%GroupBeingUninstalledText%>"

Uninstall,FileValue
"<%Status%>"

Uninstall,Message
""

Uninstall,NextButton
"<%Next%> >"

Uninstall,ProgressValue
"<%UninstallPercentComplete%>"

Uninstall,Subtitle
"Деинсталляция <%AppName%>"

Uninstall,Title
"Деинсталляция"

UninstallComplete,BackButton
"< <%Back%>"

UninstallComplete,CancelButton
"<%Cancel%>"

UninstallComplete,Caption
"Деинсталляция завершена"

UninstallComplete,Message
"<%AppName%> удалена из вашей системы."

UninstallComplete,NextButton
"<%Finish%>"

UninstallDetails,BackButton
"< <%Back%>"

UninstallDetails,CancelButton
"<%Cancel%>"

UninstallDetails,Caption
"В процессе деинсталляции произошли следующие ошибки:"

UninstallDetails,Message
""

UninstallDetails,NextButton
"<%Next%> >"

UninstallDetails,Subtitle
"В процессе удаления произошли ошибки"

UninstallDetails,Text
"<%Errors%>"

UninstallDetails,Title
"Информация о деинсталляции"

UserInformation,BackButton
"< <%Back%>"

UserInformation,CancelButton
"<%Cancel%>"

UserInformation,Caption
"Пожалуйста, введите ваше имя и название компании, в которой вы работаете."

UserInformation,CompanyLabel
"Компания:"

UserInformation,Message
""

UserInformation,NextButton
"<%Next%> >"

UserInformation,Subtitle
"Пожалуйста, введите ваши данные."

UserInformation,Title
"Информация о пользователе"

UserInformation,UserNameLabel
"Имя пользователя:"

Welcome,BackButton
"< <%Back%>"

Welcome,CancelButton
"<%Cancel%>"

Welcome,Caption
"Вас приветствует мастер установки InstallJammer для <%AppName%>"

Welcome,Message
"Мастер InstallJammer установит <%AppName%> <%Version%> на вашем компьютере.  

Перед началом установки рекомендуется закрыть все другие работающие программы.

Чтобы продолжить, выберите <%Next%>, или выберите <%Cancel%> для выхода."

Welcome,NextButton
"<%Next%> >"
