ApplicationReadmeText
"<%AppName%> LiesMich"

Back
"Zurück"

Browse
"Durchsuchen..."

BuildFileText
"Erstelle <%Tail <%FileBeingInstalled%>%>..."

BuildUninstallText
"Erstelle Deinstallation..."

Cancel
"Abbrechen"

CleanupInstallText
"Installation wird aufgeräumt..."

Close
"Schließen"

CreateDesktopShortcutText
"Desktop Verknüpfung anlegen"

CreateQuickLaunchShortcutText
"Verknüpfung Schnellstartleiste anlegen"

CustomInstallDescription
"Auswahl der benutzerdefinierten Komponenten zur Installation."

DirectoryPermissionText
"Sie haben keine Schreibberechtigung für das Verzeichnis <%Dir%>."

ExitText
"Wollen Sie dieses Setup wirklich beenden?"

FileBeingInstalledText
"Kopiere <%FileBeingInstalled%>"

FileBeingUninstalledText
"Entferne <%FileBeingUninstalled%>"

Finish
"Beenden"

GroupBeingInstalledText
"Installiere <%GroupBeingInstalled%>"

GroupBeingUninstalledText
"Entferne <%GroupBeingUninstalled%>"

Help
"Hilfe"

InstallApplicationText
"Installiere <%AppName%>"

InstallCompleteText
"Installation der Dateien fertig..."

InstallPrepareText
"Vorbereitung der Installation..."

InstallStartupText
"Dies wird <%AppName%> auf Ihrem Computer installieren. Weitermachen?"

LaunchApplicationText
"Starte <%AppName%>"

LocateJavaRuntime,PromptMessage
"Bitte sagen Sie uns, wo Ihre Java Runtime zu finden ist."

LocateJavaRuntime,StatusMessage
"Suche Java Runtime..."

Next
"Weiter"

No
"Nein"

OK
"OK"

ProgramFilesDescription
"Allgemeine Programmdateien"

RequireRootText
"Sie müssen root sein, um diese Installationsroutine auszuführen."

SeparatorText
"InstallJammer"

TextWindow,Caption
"Überschrift"

TextWindow,CloseButton
"<%Close%>"

TextWindow,Message
"Meldung kommt hier."

TextWindow,Title
"Window Titel"

TypicalInstallDescription
"Eine typische Installation."

UninstallApplicationText
"Deinstalliere <%AppName%>"

UninstallLeftoverText
"Einige Komponenten konnten nicht entfernt werden. Möchten Sie diese trotzdem löschen (nicht empfohlen)?"

UninstallPrepareText
"Vorbereitung der Deinstallation..."

UninstallStartupText
"Dies wird <%AppName%> vollkommen von Ihrem System entfernen. Wollen Sie dies\
wirklich durchführen?"

UnzipFile,StatusText
"<%FileBeingInstalledText%>"

UpdateRegistryText
"Die Windows Registry wird aktualisiert..."

VersionHelpText
"Dieses Program wird <%AppName%> Version <%Version%> installieren."

ViewReadmeText
"Liesmich ansehen"

Yes
"Ja"
