ApplicationReadmeText
"<%AppName%> Léeme"

Back
"Atrás"

Browse
"Examinar..."

BuildFileText
"Generando <%Tail <%FileBeingInstalled%>%>..."

BuildUninstallText
"Generando desinstalador..."

Cancel
"Cancelar"

CleanupInstallText
"Limpiando instalación..."

Close
"Cerrar"

CreateDesktopShortcutText
"Crear icono en Escritorio"

CreateQuickLaunchShortcutText
"Crear icono en Barra de Tareas"

CustomInstallDescription
"Seleccione los componentes de la instalación."

DirectoryPermissionText
"No tiene permisos para escribir en <%Dir%>."

ExitText
"¿Seguro que desea salir de la instalación?"

FileBeingInstalledText
"Copiando <%FileBeingInstalled%>"

FileBeingUninstalledText
"Borrando <%FileBeingUninstalled%>"

Finish
"Finalizar"

GroupBeingInstalledText
"Instalando <%GroupBeingInstalled%>..."

GroupBeingUninstalledText
"Borrando <%GroupBeingUninstalled%>"

Help
"Ayuda"

InstallApplicationText
"Instalar <%AppName%>"

InstallCompleteText
"Instalación completa..."

InstallPrepareText
"Preparando instalación..."

InstallStartupText
"Se va a instalar <%AppName%> en su equipo.  ¿Continuar?"

LaunchApplicationText
"Ejecutar <%AppName%>"

LocateJavaRuntime,PromptMessage
"Por favor, localice su Entorno de Ejecución Java (JRE)"

LocateJavaRuntime,StatusMessage
"Buscando Entorno de Ejecución Java (JRE)..."

Next
"Siguiente"

No
"No"

OK
"OK"

ProgramFilesDescription
"Archivos de Programa Comunes"

RequireRootText
"Necesita tener permisos de administrador para ejecutar el instalador."

SeparatorText
"InstallJammer"

TextWindow,Caption
"Leyenda"

TextWindow,CloseButton
"<%Close%>"

TextWindow,Message
"Mensaje aquí."

TextWindow,Title
"Título de la Ventana"

TypicalInstallDescription
"Una instalación típica."

UninstallApplicationText
"Desinstalar <%AppName%>"

UninstallLeftoverText
"Algunos componentes no pudieron ser eliminados. ¿Desea borrarlos de todos modos? (no recomendado)"

UninstallPrepareText
"Preparando desinstalación..."

UninstallStartupText
"Se eliminará completamente <%AppName%> de su sistema. ¿Seguro que desea esto?"

UnzipFile,StatusText
"<%FileBeingInstalledText%>"

UpdateRegistryText
"Actualizando Registro de Windows..."

ViewReadmeText
"Ver Léeme"

Yes
"Sí"
