ApplicationReadmeText
"<%AppName%> Readme"

Back
"Précédent"

Browse
"Parcourir..."

BuildFileText
"Génération <%Tail <%FileBeingInstalled%>%>..."

BuildUninstallText
"Génération de la désinstallation..."

Cancel
"Annuler"

CleanupInstallText
"Nettoyage de l'installation..."

Close
"Fermer"

CreateDesktopShortcutText
"Créer le raccourci sur le bureau"

CreateQuickLaunchShortcutText
"Créer un raccourci de lancement rapide"

CustomInstallDescription
"Sélectionner les composants pour l'installation."

DirectoryPermissionText
"Vous n'avez pas la permission d'écrire dans le dossier <%Dir%>."

ExitText
"Etes-vous certain de vouloir quitter ce programme d'installation?"

FileBeingInstalledText
"Copie de <%FileBeingInstalled%>"

FileBeingUninstalledText
"Suppression de <%FileBeingUninstalled%>"

Finish
"Terminer"

GroupBeingInstalledText
"Installation de <%GroupBeingInstalled%>..."

GroupBeingUninstalledText
"Suppression de <%GroupBeingUninstalled%>"

Help
"Aide"

InstallApplicationText
"Installer <%AppName%>"

InstallCompleteText
"Installation des fichiers terminée..."

InstallPrepareText
"Préparation de l'installation..."

InstallStartupText
"Ceci installera <%AppName%>  sur votre ordinateur.  Continuer?"

LaunchApplicationText
"Lancer <%AppName%>"

LocateJavaRuntime,PromptMessage
"Merci de préciser la localisation de votre Runtime Java"

LocateJavaRuntime,StatusMessage
"Localisation du Runtime Java..."

Next
"Suivant"

No
"Non"

OK
"OK"

ProgramFilesDescription
"Fichiers programme communs"

RequireRootText
"Vous devez être ROOT pour exécuter cette installeur."

SeparatorText
"InstallJammer"

TextWindow,Caption
"Légende"

TextWindow,CloseButton
"<%Close%>"

TextWindow,Message
"Saisir le message ici."

TextWindow,Title
"Titre de la fenêtre"

TypicalInstallDescription
"Une installation typique."

UninstallApplicationText
"Désinstaller <%AppName%>"

UninstallLeftoverText
"Certain composants n'ont pu être supprimés. Souhairez vous quand même les effacer (non recommandé)?"

UninstallPrepareText
"Préparation de la désinstallation..."

UninstallStartupText
"Ceci supprimera complètement <%AppName%> de votre ordinateur.  Etes-vous\
 certain de vouloir faire cela?"

UnzipFile,StatusText
"<%FileBeingInstalledText%>"

UpdateRegistryText
"Mise à jour de la base de registre Windows..."

VersionHelpText
"Ce programme va installer <%AppName%> version <%Version%>."

ViewReadmeText
"Lire le fichier Readme"

Yes
"Oui"
