ApplicationReadmeText
"<%AppName%> OlvassaEl"

Back
"Vissza"

Browse
"Tallózás..."

BuildFileText
"<%Tail <%FileBeingInstalled%>%> szerkesztése..."

BuildUninstallText
"Uninstall szerkesztése..."

Cancel
"Mégsem"

CleanupInstallText
"Telepítés takarítása..."

Close
"Bezárás"

ConsolePause,Message
"<%ConsolePauseText%>"

ConsolePauseQuitText
"-- Nyomjon egy szóközt a folytatáshoz, vagy egy 'q'-t a kilépéshez --"

ConsolePauseText
"-- Nyomjon egy szóközt a folytatáshoz --"

ConsoleSelectDestinationText
"Hova akarja telepíteni a <%AppName%> alkalmazást?"

CreateDesktopShortcutText
"Hozzon létre parancsikont az Asztalon"

CreateQuickLaunchShortcutText
"Hozzon létre a Gyorsindítóban parancsikont"

CustomInstallDescription
"Válassza ki az egyéni komponenseket a telepítéshez."

DirectoryPermissionText
"Nincs elég joga a <%Dir%> könyvtárba írni."

DisplayName
"<%AppName%>"

DownloadingFilesText
"Állományok letöltése..."

ExitText
"Biztos, hogy ki akar lépni a telepít\u0151b\u0151l?"

FileBeingInstalledText
"<%FileBeingInstalled%> másolása"

FileBeingUninstalledText
"<%FileBeingUninstalled%> törlése"

FileOverwriteText
"A <%FileBeingInstalled%> file már létezik.  Felül akarja írni?"

Finish
"Befejezés"

GroupBeingInstalledText
"<%GroupBeingInstalled%> telepítése..."

GroupBeingUninstalledText
"<%GroupBeingUninstalled%> eltávolítása"

Help
"Sugó"

InstallApplicationText
"<%AppName%> telepítése"

InstallationCompleteText
"A telepítés befejez\u0151d\u0151tt."

InstallCompleteText
"Az állomány telepítése befejez\u0151d\u0151tt..."

InstallingApplicationText
"<%AppName%> telepítése..."

InstallPrepareText
"Felkészülés a telepítésre..."

InstallStartupText
"Ez a <%AppName%> programot fogja telepíteni a számítógépére.  Folytatja?"

InstallTitleText
"<%AppName%> Setup"

LaunchApplicationText
"<%AppName%> betöltése"

LocateJavaRuntime,PromptMessage
"Kérem mondja meg, hogy a Java futtatási környezet hol található"

LocateJavaRuntime,StatusMessage
"A Java futtatási környezet keresése..."

Next
"Következ\u0151"

No
"Nem"

OK
"OK"

PasswordIncorrectText
"Érvénytelen jelszó."

ProgramFilesDescription
"Általános program állományok"

PromptForDirectoryMessage
"Kérem válasszon egy könyvtárat, majd kattintson az OK-ra."

PromptForDirectoryTitle
"Könyvtár tallózása"

PromptForRootText
"Kérem gépelje be a root jelszót."

RequireRootText
"root-nak kell lenni a telepít\u0151 futtatásához."

SeparatorText
"InstallJammer"

TextWindow,Caption
"Fejléc"

TextWindow,CloseButton
"<%Close%>"

TextWindow,Message
"Az üzenet jön ide."

TextWindow,Title
"Ablak cím"

TypicalInstallDescription
"Tipikus telepítés."

UninstallApplicationText
"<%AppName%> eltávolítása"

UninstallCompleteText
"Eltávolítás befejez\u0151d\u0151tt."

UninstallingApplicationText
"<%AppName%> eltávolítása..."

UninstallLeftoverText
"Néhány elemet nem kellene eltávolítani.\
 Mindenáron töröljük \u0151ket (nem javasolt)?"

UninstallPrepareText
"Felkészülés az eltávolításra..."

UninstallStartupText
"Ez teljesen letörli a <%AppName%> alkalmazást a rendszerér\u0151l. \
 Biztos abban, hogy ezt akarja?"

UninstallTitleText
"<%AppName%> eltávolítása"

UnpackingFilesText
"Állományok kicsomagolása..."

UnzipFile,StatusText
"<%FileBeingInstalledText%>"

UpdateRegistryText
"A Windows Registry frissítése..."

VersionHelpText
"Ez a program a <%AppName%> program <%Version%> verzióját fogja telepíteni."

ViewReadmeText
"OlvassaEl állomány elolvasása"

Yes
"Igen"
