ApplicationReadmeText
"<%AppName%> Readme"

Back
"Terug"

Browse
"Bladeren..."

BuildFileText
"Bouwen <%Tail <%FileBeingInstalled%>%>..."

BuildUninstallText
"Bouwen deïnstallatie..."

Cancel
"Annuleren"

CleanupInstallText
"Opschonen installatie..."

Close
"Sluiten"

ConsolePause,Message
"<%ConsolePauseText%>"

ConsolePauseQuitText
"-- Druk op spatie om door te gaan of op 'q' om te stoppen --"

ConsolePauseText
"-- Druk op spatie om door te gaan --"

ConsoleSelectDestinationText
"Waar wilt u <%AppName%> installeren?"

CreateDesktopShortcutText
"Maak bureaublad snelkoppeling"

CreateQuickLaunchShortcutText
"Maak Snel Start snelkoppeling"

CustomInstallDescription
"Selecteer afzonderlijke componenten voor installatie."

DirectoryPermissionText
"U heeft geen toestemming om te schrijven naar <%Dir%>."

DisplayName
"<%AppName%>"

DownloadingFilesText
"Bestanden downloaden..."

ExitText
"Weet u zeker dat u wilt stoppen met deze installatie?"

FileBeingInstalledText
"Kopiëren <%FileBeingInstalled%>"

FileBeingUninstalledText
"Verwijderen <%FileBeingUninstalled%>"

FileOverwriteText
"Het bestand <%FileBeingInstalled%> bestaat al.  Wilt u het overschrijven?"

Finish
"Klaar"

GroupBeingInstalledText
"Installeren <%GroupBeingInstalled%>..."

GroupBeingUninstalledText
"Verwijderen <%GroupBeingUninstalled%>"

Help
"Help"

InstallApplicationText
"Installeer <%AppName%>"

InstallationCompleteText
"Installatie afgerond."

InstallCompleteText
"Bestand installatie afgerond..."

InstallingApplicationText
"<%AppName%> installeren..."

InstallPrepareText
"Installatie voorbereiden..."

InstallStartupText
"Dit zal <%AppName%> op uw computer installeren.  Doorgaan?"

InstallTitleText
"<%AppName%> Setup"

LaunchApplicationText
"Start <%AppName%>"

LocateJavaRuntime,PromptMessage
"Wijs uw Java Runtime locatie aan"

LocateJavaRuntime,StatusMessage
"Java Runtime lokaliseren..."

Next
"Volgende"

No
"Nee"

OK
"OK"

PasswordIncorrectText
"Wachtwoord is onjuist."

ProgramFilesDescription
"Algemene bestanden"

PromptForDirectoryMessage
"Selecteer een directory, klik daarna op OK."

PromptForDirectoryTitle
"Blader naar map"

PromptForRootText
"Vul uw root wachtwoord in."

RequireRootText
"U moet root zijn om dit programma te installeren."

SeparatorText
"SemLab"

TextWindow,Caption
"Bijschrift"

TextWindow,CloseButton
"<%Close%>"

TextWindow,Message
"Bericht gaat hier."

TextWindow,Title
"Scherm titel"

TypicalInstallDescription
"Een standaard installatie."

UninstallApplicationText
"Verwijderen <%AppName%>"

UninstallCompleteText
"Deïnstallatie klaar."

UninstallingApplicationText
"<%AppName%> verwijderen..."

UninstallLeftoverText
"Sommige componenten konden niet worden verwijderd.  Wilt u ze toch verwijderen (niet aangeraden)?"

UninstallPrepareText
"Deïnstallatie voorbereiden..."

UninstallStartupText
"Dit verwijderd <%AppName%> geheel van uw systeem.  Weet u zeker dat u dit wilt doen?"

UninstallTitleText
"Verwijder <%AppName%>"

UnpackingFilesText
"Bestanden uitpakken..."

UnzipFile,StatusText
"<%FileBeingInstalledText%>"

UpdateRegistryText
"Windows Register bijwerken..."

VersionHelpText
"Dit programma zal <%AppName%> versie <%Version%> installeren."

ViewReadmeText
"Bekijk Readme"

Yes
"Ja"
