# -encoding utf-8

ApplicationReadmeText
"<%AppName%> Readme"

Back
"Wstecz"

Browse
"Przeglądaj..."

BuildFileText
"Budowanie <%Tail <%FileBeingInstalled%>%>..."

BuildUninstallText
"Budowanie deinstalatora..."

Cancel
"Anuluj"

CleanupInstallText
"Czyszczenie instalacji..."

Close
"Zamknij"

ConsolePause,Message
"<%ConsolePauseText%>"

ConsolePauseQuitText
"-- Wciśnij spację, aby kontynuować lub 'q', aby wyjść --"

ConsolePauseText
"-- Wciśnij spację, aby kontynuować --"

ConsoleSelectDestinationText
"Gdzie chcesz zainstalować <%AppName%>?"

CreateDesktopShortcutText
"Utwórz skrót na pulpicie"

CreateQuickLaunchShortcutText
"Utwórz skrót szybkiego uruchamiania"

CustomInstallDescription
"Zaznacz wybrane komponenty do instalacji."

DirectoryPermissionText
"Nie masz uprawniwń, aby zapisywać w <%Dir%>."

DownloadingFilesText
"Pobieranie plików..."

ExitText
"Czy na pewno chcesz opuścić instalator?"

FileBeingInstalledText
"Kopiowanie <%FileBeingInstalled%>"

FileBeingUninstalledText
"Usuwanie <%FileBeingUninstalled%>"

FileOverwriteText
"Plik <%FileBeingInstalled%> już istnieje.  Czy chcesz go naspisać?"

Finish
"Zakończ"

GroupBeingInstalledText
"Instalowanie <%GroupBeingInstalled%>..."

GroupBeingUninstalledText
"Usuwanie <%GroupBeingUninstalled%>"

Help
"Pomoc"

InstallApplicationText
"Instaluj <%AppName%>"

InstallationCompleteText
"Instalacja zakończona."

InstallCompleteText
"Instalacja pliku zakończona..."

InstallingApplicationText
"Instalowanie <%AppName%>..."

InstallPrepareText
"Przygotowywanie do instalacji..."

InstallStartupText
"Instalator zainstaluje <%AppName%> na twoim komputerze. Kontynuować?"

LaunchApplicationText
"Uruchom <%AppName%>"

LocateJavaRuntime,PromptMessage
"Proszę powiedzieć, gdzie zainstalowano Java Runtime Environment."

LocateJavaRuntime,StatusMessage
"Szukanie Java Runtime..."

Next
"Dalej"

No
"Nie"

OK
"OK"

ProgramFilesDescription
"Common Program Files"

PromptForRootText
"Proszę wpisać hasło administratora."

RequireRootText
"Musisz być administratorem (root), aby uruchomić ten instalator."

SeparatorText
"InstallJammer"

TextWindow,Caption
"Nagłówek"

TextWindow,CloseButton
"<%Close%>"

TextWindow,Message
"Wyjście wiadomości."

TextWindow,Title
"Okno tytułowe"

TypicalInstallDescription
"Instalacja typowa."

UninstallApplicationText
"Usuń <%AppName%>"

UninstallCompleteText
"Deinstalacja zakończona."

UninstallingApplicationText
"Deinstalacja <%AppName%>..."

UninstallLeftoverText
"Niektóre komponenty nie mogły zostać usunięte.  Czy pomimo to chcesz je usunąć (niezalecane)?"

UninstallPrepareText
"Przygotowywanie do deinstalacji..."

UninstallStartupText
"<%AppName%> zostanie kompletnie usunięty z twojego systemu.  Czy\
 na pewno chcesz tego?"

UnzipFile,StatusText
"<%FileBeingInstalledText%>"

UpdateRegistryText
"Uaktualnianie rejestru Windows..."

VersionHelpText
"Ten program zainstaluje <%AppName%> w wersji <%Version%>."

ViewReadmeText
"Pokaż Readme"

Yes
"Tak"
